<?php

class m140902_110055_coverage_insertion_of_insurance extends CDbMigration
{
	/*public function up()
	{
	}

	public function down()
	{
		echo "m140902_110055_coverage_insertion_of_insurance does not support migration down.\n";
		return false;
	}*/

    public function safeUp()
    {
        $this->truncateTable("dropdown_type_of_coverage_by_insurance");
        $this->execute("
            INSERT INTO `dropdown_type_of_coverage_by_insurance` (`id`, `name`, `insurance_type_id`,`create_date`, `update_date`,`created_by`,`update_by`,`language`)
             VALUES ('1', 'single coverage ', '5', null, null, null, null, 'En'),
('2', 'Family Coverage ', '5', null, null, null, null, 'En'),
('3', 'cancellation ', '6', null, null, null, null, 'En'),
('4', 'Up to € 1500, - per person ', '7', null, null, null, null, 'En'),
('5', 'Up to € 3000, - per person ', '7', null, null, null, null, 'En'),
('6', 'Up to € 4500, - per person ', '7', null, null, null, null, 'En'),
('7', 'Actual costs ', '7', null, null, null, null, 'En'),
('8', 'suitable work ', '49', null, null, null, null, 'En'),
('9', 'Common labor ', '49', null, null, null, null, 'En'),
('10', 'Occupation Labour unfitness ', '49', null, null, null, null, 'En'),
('11', 'All risk ', '18', null, null, null, null, 'En'),
('12', 'All risk oi + ', '18', null, null, null, null, 'En'),
('13', 'All risk + si ', '18', null, null, null, null, 'En'),
('14', 'All risk + rb ', '18', null, null, null, null, 'En'),
('15', 'All risk + bonus protector ', '18', null, null, null, null, 'En'),
('16', 'All risk oi + + rb ', '18', null, null, null, null, 'En'),
('17', 'All risk si + + rb ', '18', null, null, null, null, 'En'),
('18', 'All risk oi + bonus + protector ', '18', null, null, null, null, 'En'),
('19', 'All risk si + + bonus protector ', '18', null, null, null, null, 'En'),
('20', 'All risk + rb + bonus protector ', '18', null, null, null, null, 'En'),
('21', 'All risk oi + + rb + bonus protector ', '18', null, null, null, null, 'En'),
('22', 'All risk si + + rb + bonus protector ', '18', null, null, null, null, 'En'),
('23', 'WA limited airframe ', '18', null, null, null, null, 'En'),
('24', 'WA limited airframe + oi ', '18', null, null, null, null, 'En'),
('25', 'WA limited airframe + si ', '18', null, null, null, null, 'En'),
('26', 'WA limited airframe + rb ', '18', null, null, null, null, 'En'),
('27', 'WA limited airframe + bonus protector ', '18', null, null, null, null, 'En'),
('28', 'WA limited airframe + oi + rb ', '18', null, null, null, null, 'En'),
('29', 'WA limited airframe si + + rb ', '18', null, null, null, null, 'En'),
('30', 'WA limited airframe + oi + bonus protector ', '18', null, null, null, null, 'En'),
('31', 'WA limited airframe + Si + bonus protector ', '18', null, null, null, null, 'En'),
('32', 'WA limited airframe + rb + bonus protector ', '18', null, null, null, null, 'En'),
('33', 'WA limited airframe + oi + rb + bonus protector ', '18', null, null, null, null, 'En'),
('34', 'WA limited airframe + Si + rb + bonus protector ', '18', null, null, null, null, 'En'),
('35', 'WA ', '18', null, null, null, null, 'En'),
('36', 'WA + oi ', '18', null, null, null, null, 'En'),
('37', 'WA + si ', '18', null, null, null, null, 'En'),
('38', 'WA + rb ', '18', null, null, null, null, 'En'),
('39', 'WA + bonus protector ', '18', null, null, null, null, 'En'),
('40', 'WA + oi + rb ', '18', null, null, null, null, 'En'),
('41', 'WA si + + rb ', '18', null, null, null, null, 'En'),
('42', 'WA + oi + bonus protector ', '18', null, null, null, null, 'En'),
('43', 'WA + si + bonus protector ', '18', null, null, null, null, 'En'),
('44', 'WA + rb + bonus protector ', '18', null, null, null, null, 'En'),
('45', 'WA + oi + rb + bonus protector ', '18', null, null, null, null, 'En'),
('46', 'WA si + + rb + bonus protector ', '18', null, null, null, null, 'En'),
('47', 'business Liability Insurance ', '31', null, null, null, null, 'En'),
('48', 'extensive ', '32', null, null, null, null, 'En'),
('49', 'Advanced + Glass ', '32', null, null, null, null, 'En'),
('50', 'additional extended ', '32', null, null, null, null, 'En'),
('51', 'Extra wide glass + ', '32', null, null, null, null, 'En'),
('52', 'extensive ', '33', null, null, null, null, 'En'),
('53', 'additional extended ', '33', null, null, null, null, 'En'),
('54', 'investment insurance ', '50', null, null, null, null, 'En'),
('55', 'professional Liability Insurance ', '34', null, null, null, null, 'En'),
('56', 'All risk ', '19', null, null, null, null, 'En'),
('57', 'All risk oi + ', '19', null, null, null, null, 'En'),
('58', 'All risk + si ', '19', null, null, null, null, 'En'),
('59', 'All risk + rb ', '19', null, null, null, null, 'En'),
('60', 'All risk oi + + rb ', '19', null, null, null, null, 'En'),
('61', 'All risk si + + rb ', '19', null, null, null, null, 'En'),
('62', 'WA limited airframe ', '19', null, null, null, null, 'En'),
('63', 'WA limited airframe + oi ', '19', null, null, null, null, 'En'),
('64', 'WA limited airframe + si ', '19', null, null, null, null, 'En'),
('65', 'WA limited airframe + rb ', '19', null, null, null, null, 'En'),
('66', 'WA limited airframe + oi + rb ', '19', null, null, null, null, 'En'),
('67', 'WA limited airframe si + + rb ', '19', null, null, null, null, 'En'),
('68', 'WA ', '19', null, null, null, null, 'En'),
('69', 'WA + oi ', '19', null, null, null, null, 'En'),
('70', 'WA + si ', '19', null, null, null, null, 'En'),
('71', 'WA + rb ', '19', null, null, null, null, 'En'),
('72', 'WA + oi + rb ', '19', null, null, null, null, 'En'),
('73', 'WA si + + rb ', '19', null, null, null, null, 'En'),
('74', 'All risk ', '21', null, null, null, null, 'En'),
('75', 'All risks + accidents opzittende', '21', null, null, null, null, 'En'),
('76', 'All risks of accidents opzittende + + rb ', '21', null, null, null, null, 'En'),
('77', 'All risk + rb ', '21', null, null, null, null, 'En'),
('78', 'WA limited airframe ', '21', null, null, null, null, 'En'),
('79', 'WA limited airframe + accidents opzittende ', '21', null, null, null, null, 'En'),
('80', 'WA limited airframe + accident + rb opzittende ', '21', null, null, null, null, 'En'),
('81', 'WA limited airframe + rb ', '21', null, null, null, null, 'En'),
('82', 'WA ', '21', null, null, null, null, 'En'),
('83', 'WA + accidents opzittende ', '21', null, null, null, null, 'En'),
('84', 'WA + accident + rb opzittende ', '21', null, null, null, null, 'En'),
('85', 'WA + rb ', '21', null, null, null, null, 'En'),
('86', 'standard ', '48', null, null, null, null, 'En'),
('87', 'bespoke ', '48', null, null, null, null, 'En'),
('88', 'All risk ', '24', null, null, null, null, 'En'),
('89', 'WA limited airframe ', '24', null, null, null, null, 'En'),
('90', 'WA ', '24', null, null, null, null, 'En'),
('91', '1. Discontinue ', '41', null, null, null, null, 'En'),
('92', '2. Absence of people + 1 ', '41', null, null, null, null, 'En'),
('93', '3. Liability + 1 and 2 ', '41', null, null, null, null, 'En'),
('94', '4. Accidents + 1,2, and 3 ', '41', null, null, null, null, 'En'),
('95', '5. Rain + 1,2,3, and 4 ', '41', null, null, null, null, 'En'),
('96', '6. + Object 1,2,3,4, and 5 ', '41', null, null, null, null, 'En'),
('97', 'Current ', '27', null, null, null, null, 'En'),
('98', 'continuously ', '27', null, null, null, null, 'En'),
('99', 'garage Insurance ', '36', null, null, null, null, 'En'),
('100', 'Damage and theft ', '28', null, null, null, null, 'En'),
('101', 'standard ', '29', null, null, null, null, 'En'),
('102', 'hybrid Insurance ', null, null, null, null, null, 'En'),
('103', 'extensive ', '1', null, null, null, null, 'En'),
('104', 'additional extended ', '1', null, null, null, null, 'En'),
('105', 'All risk ', '1', null, null, null, null, 'En'),
('106', 'Advanced + Glass ', '1', null, null, null, null, 'En'),
('107', 'Extra wide glass + ', '1', null, null, null, null, 'En'),
('108', 'All risk + glass ', '1', null, null, null, null, 'En'),
('109', 'Fire, explosion and lightning (PDO) ', '47', null, null, null, null, 'En'),
('110', 'BOB + aircraft damage and storm damage ', '47', null, null, null, null, 'En'),
('111', 'extensive ', '47', null, null, null, null, 'En'),
('112', 'BOB + glass ', '47', null, null, null, null, 'En'),
('113', 'BOB + Aircraft Damage and storm damage + glass ', '47', null, null, null, null, 'En'),
('114', 'Advanced + Glass ', '47', null, null, null, null, 'En'),
('115', 'All risk ', '47', null, null, null, null, 'En'),
('116', 'All risk + glass ', '47', null, null, null, null, 'En'),
('117', 'All risk ', '25', null, null, null, null, 'En'),
('118', 'All risk oi + ', '25', null, null, null, null, 'En'),
('119', 'All risk + si ', '25', null, null, null, null, 'En'),
('120', 'All risk + rb ', '25', null, null, null, null, 'En'),
('121', 'All risks + possessions ', '25', null, null, null, null, 'En'),
('122', 'All risk oi + + rb ', '25', null, null, null, null, 'En'),
('123', 'All risk si + + rb ', '25', null, null, null, null, 'En'),
('124', 'All risk oi + + contents ', '25', null, null, null, null, 'En'),
('125', 'All risk si + + contents ', '25', null, null, null, null, 'En'),
('126', 'All risk rb + + contents ', '25', null, null, null, null, 'En'),
('127', 'All risk oi + + + rb contents ', '25', null, null, null, null, 'En'),
('128', 'All risk si + + rb + contents ', '25', null, null, null, null, 'En'),
('129', 'WA limited airframe ', '25', null, null, null, null, 'En'),
('130', 'WA limited airframe + oi ', '25', null, null, null, null, 'En'),
('131', 'WA limited airframe + si ', '25', null, null, null, null, 'En'),
('132', 'WA limited airframe + rb ', '25', null, null, null, null, 'En'),
('133', 'WA limited airframe + contents ', '25', null, null, null, null, 'En'),
('134', 'WA limited airframe + oi + rb ', '25', null, null, null, null, 'En'),
('135', 'WA limited airframe si + + rb ', '25', null, null, null, null, 'En'),
('136', 'WA limited airframe + oi + contents ', '25', null, null, null, null, 'En'),
('137', 'WA limited airframe si + + contents ', '25', null, null, null, null, 'En'),
('138', 'WA limited airframe + rb + contents ', '25', null, null, null, null, 'En'),
('139', 'WA limited airframe + oi + rb + contents ', '25', null, null, null, null, 'En'),
('140', 'WA limited airframe + j + + rb contents ', '25', null, null, null, null, 'En'),
('141', 'WA ', '25', null, null, null, null, 'En'),
('142', 'WA + oi ', '25', null, null, null, null, 'En'),
('143', 'WA + si ', '25', null, null, null, null, 'En'),
('144', 'WA + rb ', '25', null, null, null, null, 'En'),
('145', 'WA + contents ', '25', null, null, null, null, 'En'),
('146', 'WA + oi + rb ', '25', null, null, null, null, 'En'),
('147', 'WA si + + rb ', '25', null, null, null, null, 'En'),
('148', 'WA + oi + contents ', '25', null, null, null, null, 'En'),
('149', 'WA si + + contents ', '25', null, null, null, null, 'En'),
('150', 'WA + rb + contents ', '25', null, null, null, null, 'En'),
('151', 'WA oi + + + rb contents ', '25', null, null, null, null, 'En'),
('152', 'WA si + + rb + contents ', '25', null, null, null, null, 'En'),
('153', 'endowment ', '51', null, null, null, null, 'En'),
('154', 'valuables Coverage ', '3', null, null, null, null, 'En'),
('155', 'Mixed policy, one life ', '52', null, null, null, null, 'En'),
('156', 'Mixed policy, two lives ', '52', null, null, null, null, 'En'),
('157', 'fixed term ', '52', null, null, null, null, 'En'),
('158', 'Policy with refund ', '52', null, null, null, null, 'En'),
('159', 'Directly entering temporary, one life insurance policy ', '8', null, null, null, null, 'En'),
('160', 'Directly entering temporary, two lives, policy ', '8', null, null, null, null, 'En'),
('161', 'Directly entering life, one life insurance policy ', '8', null, null, null, null, 'En'),
('162', 'Directly entering life, two lives, policy ', '8', null, null, null, null, 'En'),
('163', 'Deferred annuity, policy ', '8', null, null, null, null, 'En'),
('164', 'Directly entering temporary, one life, bank savings ', '8', null, null, null, null, 'En'),
('165', 'Directly entering temporary, two lives, bank savings ', '8', null, null, null, null, 'En'),
('166', 'Directly entering life, one life, bank savings ', '8', null, null, null, null, 'En'),
('167', 'Directly entering life, two lives, bank savings ', '8', null, null, null, null, 'En'),
('168', 'Deferred annuity, bank savings ', '8', null, null, null, null, 'En'),
('169', 'WA ', '37', null, null, null, null, 'En'),
('170', 'All risk ', '37', null, null, null, null, 'En'),
('171', 'WA ', '38', null, null, null, null, 'En'),
('172', 'WA limited airframe ', '38', null, null, null, null, 'En'),
('173', 'All risk ', '38', null, null, null, null, 'En'),
('174', 'All risk ', '4', null, null, null, null, 'En'),
('175', 'All risk ', '20', null, null, null, null, 'En'),
('176', 'All risks + accidents opzittende ', '20', null, null, null, null, 'En'),
('177', 'All risks of accidents opzittende + + rb ', '20', null, null, null, null, 'En'),
('178', 'All risk + rb ', '20', null, null, null, null, 'En'),
('179', 'WA limited airframe ', '20', null, null, null, null, 'En'),
('180', 'WA limited airframe + accidents opzittende ', '20', null, null, null, null, 'En'),
('181', 'WA limited airframe + accident + rb opzittende ', '20', null, null, null, null, 'En'),
('182', 'WA limited airframe + rb ', '20', null, null, null, null, 'En'),
('183', 'WA ', '20', null, null, null, null, 'En'),
('184', 'WA + accidents opzittende ', '20', null, null, null, null, 'En'),
('185', 'WA + accident + rb opzittende ', '20', null, null, null, null, 'En'),
('186', 'WA + rb ', '20', null, null, null, null, 'En'),
('187', 'All risk ', '22', null, null, null, null, 'En'),
('188', 'All risks +  accidents opzittende ', '22', null, null, null, null, 'En'),
('189', 'All risks of accidents opzittende + + rb ', '22', null, null, null, null, 'En'),
('190', 'All risk + rb ', '22', null, null, null, null, 'En'),
('191', 'WA limited airframe ', '22', null, null, null, null, 'En'),
('192', 'WA limited airframe + accidents opzittende ', '22', null, null, null, null, 'En'),
('193', 'WA limited airframe + accident + rb opzittende ', '22', null, null, null, null, 'En'),
('194', 'WA limited airframe + rb ', '22', null, null, null, null, 'En'),
('195', 'WA ', '22', null, null, null, null, 'En'),
('196', 'WA + accidents opzittende ', '22', null, null, null, null, 'En'),
('197', 'WA + accident + rb opzittende ', '22', null, null, null, null, 'En'),
('198', 'WA + rb ', '22', null, null, null, null, 'En'),
('199', 'single ', '14', null, null, null, null, 'En'),
('200', 'Single with children ', '14', null, null, null, null, 'En'),
('201', 'family ', '14', null, null, null, null, 'En'),
('202', 'Family with children ', '14', null, null, null, null, 'En'),
('203', 'extensive ', '2', null, null, null, null, 'En'),
('204', 'additional extended ', '2', null, null, null, null, 'En'),
('205', 'All risk ', '2', null, null, null, null, 'En'),
('206', 'Advanced + Glass ', '2', null, null, null, null, 'En'),
('207', 'Extra wide glass + ', '2', null, null, null, null, 'En'),
('208', 'All risk + glass ', '2', null, null, null, null, 'En'),
('209', 'Consistently one life ', '15', null, null, null, null, 'En'),
('210', 'Consistently 2 lives ', '15', null, null, null, null, 'En'),
('211', 'Annuity falling, one life ', '15', null, null, null, null, 'En'),
('212', 'Annuity falling, two lives ', '15', null, null, null, null, 'En'),
('213', 'Decreasing linearly, one life ', '15', null, null, null, null, 'En'),
('214', 'Decreasing linearly, two lives ', '15', null, null, null, null, 'En'),
('215', 'In case of death ', '30', null, null, null, null, 'En'),
('216', 'In case of death + accident ', '30', null, null, null, null, 'En'),
('217', 'extensive ', '30', null, null, null, null, 'En'),
('218', 'packet ', '17', null, null, null, null, 'En'),
('219', 'WA ', '26', null, null, null, null, 'En'),
('220', 'WA + fire ', '26', null, null, null, null, 'En'),
('221', 'WA + theft ', '26', null, null, null, null, 'En'),
('222', 'WA + fire and theft ', '26', null, null, null, null, 'En'),
('223', 'All risk ', '26', null, null, null, null, 'En'),
('224', '1. Traffic ', '9', null, null, null, null, 'En'),
('225', '2. Consumer and live + 1 ', '9', null, null, null, null, 'En'),
('226', '3. Income + 1 and 2 ', '9', null, null, null, null, 'En'),
('227', '4. Fiscal and power + 1,2 and 3 ', '9', null, null, null, null, 'En'),
('228', '5. Mediation in divorce + 1, 2,3 and 4 ', '9', null, null, null, null, 'En'),
('229', 'luggage ', '10', null, null, null, null, 'En'),
('230', 'Baggage + medical expense', '10', null, null, null, null, 'En'),
('231', 'Baggage + accident ', '10', null, null, null, null, 'En'),
('232', 'Baggage + dangerous sports ', '10', null, null, null, null, 'En'),
('233', 'Baggage + money ', '10', null, null, null, null, 'En'),
('234', 'Baggage + Cancellation ', '10', null, null, null, null, 'En'),
('235', 'combination ', '10', null, null, null, null, 'En'),
('236', 'luggage ', '11', null, null, null, null, 'En'),
('237', 'Baggage + medical expense', '11', null, null, null, null, 'En'),
('238', 'Baggage + accident ', '11', null, null, null, null, 'En'),
('239', 'Baggage + dangerous sports ', '11', null, null, null, null, 'En'),
('240', 'Baggage + money ', '11', null, null, null, null, 'En'),
('241', 'Baggage + Cancellation ', '11', null, null, null, null, 'En'),
('242', 'combination ', '11', null, null, null, null, 'En'),
('243', '1 person coverage in cash ', '12', null, null, null, null, 'En'),
('244', 'Family Coverage in cash ', '12', null, null, null, null, 'En'),
('245', '1 person coverage in kind ', '12', null, null, null, null, 'En'),
('246', 'Family coverage in kind ', '12', null, null, null, null, 'En'),
('247', 'All risk ', '39', null, null, null, null, 'En'),
('248', 'All risk oi + ', '39', null, null, null, null, 'En'),
('249', 'All risk + si ', '39', null, null, null, null, 'En'),
('250', 'All risk + rb ', '39', null, null, null, null, 'En'),
('251', 'All risk oi + + rb ', '39', null, null, null, null, 'En'),
('252', 'All risk si + + rb ', '39', null, null, null, null, 'En'),
('253', 'WA limited airframe ', '39', null, null, null, null, 'En'),
('254', 'WA limited airframe + oi ', '39', null, null, null, null, 'En'),
('255', 'WA limited airframe + si ', '39', null, null, null, null, 'En'),
('256', 'WA limited airframe + rb ', '39', null, null, null, null, 'En'),
('257', 'WA limited airframe + oi + rb ', '39', null, null, null, null, 'En'),
('258', 'WA limited airframe si + + rb ', '39', null, null, null, null, 'En'),
('259', 'WA ', '39', null, null, null, null, 'En'),
('260', 'WA + oi ', '39', null, null, null, null, 'En'),
('261', 'WA + si ', '39', null, null, null, null, 'En'),
('262', 'WA + rb ', '39', null, null, null, null, 'En'),
('263', 'WA + oi + rb ', '39', null, null, null, null, 'En'),
('264', 'WA si + + rb ', '39', null, null, null, null, 'En'),
('265', 'fleet Coverage ', '40', null, null, null, null, 'En'),
('266', 'basis ', '42', null, null, null, null, 'En'),
('267', 'Basic + transport ', '42', null, null, null, null, 'En'),
('268', 'Base + live / work ', '42', null, null, null, null, 'En'),
('269', 'Basic + transport + live / work ', '42', null, null, null, null, 'En'),
('270', 'Damage and theft ', '13', null, null, null, null, 'En'),
('271', 'conventional ', '43', null, null, null, null, 'En'),
('272', 'stoploss ', '43', null, null, null, null, 'En');





        ");
    }

    public function safeDown()
    {
        $this->truncateTable("dropdown_type_of_coverage_by_insurance");
    }


}