<?php

class m140811_113041_insert_data_to_dropdowns extends CDbMigration
{
	/*public function up()
	{
	}

	public function down()
	{
		echo "m140811_113041_insert_data_to_dropdowns does not support migration down.\n";
		return false;
	}*/


	// Use safeUp/safeDown to do migration with transaction
	public function safeUp()
	{
        $this->execute("
            INSERT INTO `dropdown_banks` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'ABN Amro ', NULL, NULL),
            (2, 'AEGON Bank ', NULL, NULL),
            (3, 'Akbank ', NULL, NULL),
            (4, 'Alex ', NULL, NULL),
            (5, 'Amsterdam Trade Bank ', NULL, NULL),
            (6, 'Anadolubank ', NULL, NULL),
            (7, 'Argenta ', NULL, NULL),
            (8, 'ASN Bank ', NULL, NULL),
            (9, 'Bank Bercoop ', NULL, NULL),
            (10, 'Bank Insinger de Beaufort ', NULL, NULL),
            (11, 'Bank of Scotland ', NULL, NULL),
            (12, 'Bank ten Cate ', NULL, NULL),
            (13, 'Banque Artesia ', NULL, NULL),
            (14, 'BinckBank ', NULL, NULL),
            (15, 'Bizner Bank ', NULL, NULL),
            (16, 'BLG ', NULL, NULL),
            (17, 'CenE Bankiers ', NULL, NULL),
            (18, 'Centraal Beheer Achmea ', NULL, NULL),
            (19, 'Crediam ', NULL, NULL),
            (20, 'Credit Europe Bank ', NULL, NULL),
            (21, 'Delta Lloyd ', NULL, NULL),
            (22, 'DHB Bank ', NULL, NULL),
            (23, 'DSB Bank ', NULL, NULL),
            (24, 'Stroeve ', NULL, NULL),
            (25, 'Florius ', NULL, NULL),
            (26, 'Fortis Bank ', NULL, NULL),
            (27, 'Friesland Bank ', NULL, NULL),
            (28, 'Garanti Bank ', NULL, NULL),
            (29, 'Dutch Union Bank ', NULL, NULL),
            (30, 'Hypotrust ', NULL, NULL),
            (31, 'ING Bank ', NULL, NULL),
            (32, 'InterBank ', NULL, NULL),
            (33, 'Kas Bank ', NULL, NULL),
            (34, 'Kempen ', NULL, NULL),
            (35, 'MoneYou ', NULL, NULL),
            (36, 'Nationale Nederlanden ', NULL, NULL),
            (37, 'NIBC Direct ', NULL, NULL),
            (38, 'Obvion ', NULL, NULL),
            (39, 'OHRA Bank ', NULL, NULL),
            (40, 'Rabobank ', NULL, NULL),
            (41, 'Robeco Direct ', NULL, NULL),
            (42, 'Robein Bank ', NULL, NULL),
            (43, 'Santander ', NULL, NULL),
            (44, 'Schretlen ', NULL, NULL),
            (45, 'SNS Bank ', NULL, NULL),
            (46, 'RegioBank ', NULL, NULL),
            (47, 'Staalbankiers ', NULL, NULL),
            (48, 'TEB The Economy Bank ', NULL, NULL),
            (49, 'Triodos Bank ', NULL, NULL),
            (50, 'Van Lanschot Bankiers ', NULL, NULL),
            (51, 'WestlandUtrecht Hypotheekbank ', NULL, NULL);

            INSERT INTO `dropdown_car_insurance_mileage_per_year` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'unlimited ', NULL, NULL),
            (2, '5,000 km ', NULL, NULL),
            (3, '7,500 km ', NULL, NULL),
            (4, '8,000 km ', NULL, NULL),
            (5, '12,000 miles ', NULL, NULL),
            (6, '15,000 miles ', NULL, NULL),
            (7, '20,000 miles ', NULL, NULL),
            (8, '25,000 miles ', NULL, NULL);

            INSERT INTO `dropdown_county` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Brabant ', NULL, NULL),
            (2, 'Friesland ', NULL, NULL),
            (3, 'Utrecht ', NULL, NULL),
            (4, 'Noord-Holland ', NULL, NULL),
            (5, 'Groningen ', NULL, NULL),
            (6, 'Drenthe ', NULL, NULL),
            (7, 'on Lille ', NULL, NULL),
            (8, 'Flevoland ', NULL, NULL),
            (9, 'Limburg ', NULL, NULL),
            (10, 'Zealand ', NULL, NULL),
            (11, 'South Holland ', NULL, NULL),
            (12, 'Gelderland ', NULL, NULL);

            INSERT INTO `dropdown_credit_banks` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'ABN Amro ', NULL, NULL),
            (2, 'Arenda ', NULL, NULL),
            (3, 'becam ', NULL, NULL),
            (4, 'Credivance ', NULL, NULL),
            (5, 'DEFAM ', NULL, NULL),
            (6, 'DHB Bank ', NULL, NULL),
            (7, 'FBTO ', NULL, NULL),
            (8, 'Fortis Bank ', NULL, NULL),
            (9, 'Freo ', NULL, NULL),
            (10, 'Friesland Bank ', NULL, NULL),
            (11, 'Frisia financing ', NULL, NULL),
            (12, 'HDV ', NULL, NULL),
            (13, 'Dutch Banking Union ', NULL, NULL),
            (14, 'ING Bank ', NULL, NULL),
            (15, 'InterBank ', NULL, NULL),
            (16, 'MoneYou ', NULL, NULL),
            (17, 'Post Credit ', NULL, NULL),
            (18, 'Prime Line ', NULL, NULL),
            (19, 'Rabobank ', NULL, NULL),
            (20, 'Ribank ', NULL, NULL),
            (21, 'Santander ', NULL, NULL),
            (22, 'SNS Bank ', NULL, NULL),
            (23, 'RegioBank ', NULL, NULL);

            INSERT INTO `dropdown_credit_card_banks` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Rabobank Goldcard ', NULL, NULL),
            (2, 'Rabocard ', NULL, NULL),
            (3, 'ABN AMRO Gold Card ', NULL, NULL),
            (4, 'ING Card Platinum ', NULL, NULL),
            (5, 'ING Card Classic ', NULL, NULL),
            (6, 'SNS Credit ', NULL, NULL),
            (7, 'ABN Amro Credit Card ', NULL, NULL),
            (8, 'Visa Greencard ', NULL, NULL),
            (9, 'Visa The World Card ', NULL, NULL),
            (10, 'ANWB Visa Cards ', NULL, NULL),
            (11, 'ANWB Mastercard ', NULL, NULL),
            (12, 'ANWB Visa Gold Card ', NULL, NULL),
            (13, 'Ohra Visa Card ', NULL, NULL),
            (14, 'Panda Visa Card ', NULL, NULL),
            (15, 'BIJcard ', NULL, NULL),
            (16, 'American Express Flying Blue ', NULL, NULL),
            (17, 'American Express Gold ', NULL, NULL),
            (18, 'American Express Classic ', NULL, NULL),
            (19, 'American Express Platinum ', NULL, NULL);

            INSERT INTO `dropdown_department` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'claims department ', NULL, NULL),
            (2, 'mortgage department ', NULL, NULL),
            (3, 'Within Service Department ', NULL, NULL),
            (4, 'pension division ', NULL, NULL),
            (5, 'credit department ', NULL, NULL),
            (6, 'insurance department ', NULL, NULL),
            (7, 'Financial Planning Department ', NULL, NULL);

            INSERT INTO `dropdown_document_type` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'mortgages ', NULL, NULL),
            (2, 'insurance ', NULL, NULL),
            (3, 'pensions ', NULL, NULL),
            (4, 'credits ', NULL, NULL),
            (5, 'request form ', NULL, NULL),
            (6, 'quotation Form ', NULL, NULL),
            (7, 'accident report ', NULL, NULL);

            INSERT INTO `dropdown_family_composition` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'single ', NULL, NULL),
            (2, 'Single with 1 child ', NULL, NULL),
            (3, 'Single with several children ', NULL, NULL),
            (4, 'Families without children ', NULL, NULL),
            (5, 'Family with one child ', NULL, NULL),
            (6, 'Family with several children ', NULL, NULL);

            INSERT INTO `dropdown_functions` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Within Service Employee ', NULL, NULL),
            (2, 'damage advisor ', NULL, NULL),
            (3, 'mortgage advisor ', NULL, NULL),
            (4, 'retirement advisor ', NULL, NULL),
            (5, 'credit advisor ', NULL, NULL),
            (6, 'insurance advisor ', NULL, NULL),
            (7, 'financial Planner ', NULL, NULL);



            INSERT INTO `dropdown_insurers` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'ABN AMRO ', NULL, NULL),
            (2, 'ABP ', NULL, NULL),
            (3, 'Aegon ', NULL, NULL),
            (4, 'Agis Health insurer ', NULL, NULL),
            (5, 'AgriVer ', NULL, NULL),
            (6, 'AIG Europe SA ', NULL, NULL),
            (7, 'general Interest ', NULL, NULL),
            (8, 'Allianz Netherlands ', NULL, NULL),
            (9, 'Allsecur ', NULL, NULL),
            (10, 'AnderZorg ', NULL, NULL),
            (11, 'anchor Group ', NULL, NULL),
            (12, 'anchor Legal ', NULL, NULL),
            (13, 'ANWB ', NULL, NULL),
            (14, 'ARAG ', NULL, NULL),
            (15, 'Ardanta ', NULL, NULL),
            (16, 'ASR Insurance ', NULL, NULL),
            (17, 'Avéro Achmea ', NULL, NULL),
            (18, 'Azivo ', NULL, NULL),
            (19, 'Bloemers Nassau ', NULL, NULL),
            (20, 'Bruns ten Brink Underwriters BV ', NULL, NULL),
            (21, 'Centraal Beheer Achmea ', NULL, NULL),
            (22, 'Confior ', NULL, NULL),
            (23, 'Conservatrix ', NULL, NULL),
            (24, 'Cordares ', NULL, NULL),
            (25, 'CUVO ', NULL, NULL),
            (26, 'CZ ', NULL, NULL),
            (27, 'DAS ', NULL, NULL),
            (28, 'DBV Insurance ', NULL, NULL),
            (29, 'the Amersfoort ', NULL, NULL),
            (30, 'The Friesland Zorgverzekeraar ', NULL, NULL),
            (31, 'DELA ', NULL, NULL),
            (32, 'Delta Lloyd ', NULL, NULL),
            (33, 'Ditzo ', NULL, NULL),
            (34, 'DVZ Achmea ', NULL, NULL),
            (35, 'Erasmus Insurance ', NULL, NULL),
            (36, 'Ergo Life ', NULL, NULL),
            (37, 'ETI ', NULL, NULL),
            (38, 'Falcon Leven ', NULL, NULL),
            (39, 'FBTO ', NULL, NULL),
            (40, 'Gelder Funeral Insurance ', NULL, NULL),
            (41, 'Generali ', NULL, NULL),
            (42, 'Gouda Insurance ', NULL, NULL),
            (43, 'Groene Land Achmea ', NULL, NULL),
            (44, 'HDB Assen ', NULL, NULL),
            (45, 'HEMA ', NULL, NULL),
            (46, 'Ineas ', NULL, NULL),
            (47, 'ING Bank ', NULL, NULL),
            (48, 'InShared ', NULL, NULL),
            (49, 'Interpolis ', NULL, NULL),
            (50, 'IZA ', NULL, NULL),
            (51, 'iZio ', NULL, NULL),
            (52, 'IZZ ', NULL, NULL),
            (53, 'cloverleaf Insurance ', NULL, NULL),
            (54, 'Legal & General ', NULL, NULL),
            (55, 'London Insurance ', NULL, NULL),
            (56, 'Loyalis ', NULL, NULL),
            (57, 'menzis ', NULL, NULL),
            (58, 'Mondial Assistance ', NULL, NULL),
            (59, 'Monuta ', NULL, NULL),
            (60, 'Movir ', NULL, NULL),
            (61, 'National Academic ', NULL, NULL),
            (62, 'Nationale Nederlanden ', NULL, NULL),
            (63, 'Noordhollandsche 1816 ', NULL, NULL),
            (64, 'Nuvema ', NULL, NULL),
            (65, 'OHRA ', NULL, NULL),
            (66, 'Mutual Aid Insurance ', NULL, NULL),
            (67, 'Onna-Onna ', NULL, NULL),
            (68, 'ONVZ Zorgverzekeraar ', NULL, NULL),
            (69, 'OOM Insurance ', NULL, NULL),
            (70, 'Orion Direct ', NULL, NULL),
            (71, 'OZF Achmea ', NULL, NULL),
            (72, 'Paerel Life ', NULL, NULL),
            (73, 'PC Uitvaartzorg ', NULL, NULL),
            (74, 'PGGM ', NULL, NULL),
            (75, 'PNO ', NULL, NULL),
            (76, 'Polis Direct ', NULL, NULL),
            (77, 'Prolife ', NULL, NULL),
            (78, 'Proteq Animal ', NULL, NULL),
            (79, 'Proteq Direct ', NULL, NULL),
            (80, 'PVF Achmea ', NULL, NULL),
            (81, 'PWZ Achmea ', NULL, NULL),
            (82, 'Queens ', NULL, NULL),
            (83, 'REAAL Insurance ', NULL, NULL),
            (84, 'Robein Life ', NULL, NULL),
            (85, 'stainless Steel ', NULL, NULL),
            (86, 'salland insurance ', NULL, NULL),
            (87, 'SNS Bank ', NULL, NULL),
            (88, 'Holland City Health insurer ', NULL, NULL),
            (89, 'SZVK ', NULL, NULL),
            (90, 'TakeCareNow ', NULL, NULL),
            (91, 'Trias Health Insurance ', NULL, NULL),
            (92, 'Turien ', NULL, NULL),
            (93, 'TVM Insurance ', NULL, NULL),
            (94, 'Unigarant ', NULL, NULL),
            (95, 'Unive Insurance ', NULL, NULL),
            (96, 'VvAA ', NULL, NULL),
            (97, 'Residential Mortgage Fund ', NULL, NULL),
            (98, 'Silver Cross Achmea ', NULL, NULL),
            (99, 'ZLM Insurance ', NULL, NULL),
            (100, 'Care and Security ', NULL, NULL),
            (101, 'Health insurer DSW ', NULL, NULL),
            (102, 'Health insurer VGZ ', NULL, NULL),
            (103, 'Zwitserleven ', NULL, NULL);

            INSERT INTO `dropdown_insurer_for_redemption_of_mortgage` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'CZ ', NULL, NULL),
            (2, 'DAS ', NULL, NULL),
            (3, 'DBV Insurance ', NULL, NULL),
            (4, 'the Amersfoort ', NULL, NULL),
            (5, 'The Friesland Zorgverzekeraar ', NULL, NULL),
            (6, 'DELA ', NULL, NULL),
            (7, 'Delta Lloyd ', NULL, NULL),
            (8, 'DHB Bank ', NULL, NULL),
            (9, 'Ditzo ', NULL, NULL),
            (10, 'DSB Bank ', NULL, NULL),
            (11, 'DVZ Achmea ', NULL, NULL),
            (12, 'Stroeve ', NULL, NULL),
            (13, 'Erasmus Insurance ', NULL, NULL),
            (14, 'Ergo Life ', NULL, NULL),
            (15, 'ETI ', NULL, NULL),
            (16, 'Falcon Leven ', NULL, NULL),
            (17, 'FBTO ', NULL, NULL),
            (18, 'Florius ', NULL, NULL),
            (19, 'Fortis Bank ', NULL, NULL),
            (20, 'Friesland Bank ', NULL, NULL),
            (21, 'Garanti Bank ', NULL, NULL),
            (22, 'Gelder Funeral Insurance ', NULL, NULL),
            (23, 'Generali ', NULL, NULL),
            (24, 'Gouda Insurance ', NULL, NULL),
            (25, 'Groene Land Achmea ', NULL, NULL),
            (26, 'HDB Assen ', NULL, NULL),
            (27, 'HEMA ', NULL, NULL),
            (28, 'Dutch Union Bank ', NULL, NULL),
            (29, 'Hypotrust ', NULL, NULL),
            (30, 'Ineas ', NULL, NULL),
            (31, 'ING Bank ', NULL, NULL),
            (32, 'InShared ', NULL, NULL),
            (33, 'InterBank ', NULL, NULL),
            (34, 'Interpolis ', NULL, NULL),
            (35, 'IZA ', NULL, NULL),
            (36, 'iZio ', NULL, NULL),
            (37, 'IZZ ', NULL, NULL),
            (38, 'Kas Bank ', NULL, NULL),
            (39, 'Kempen ', NULL, NULL),
            (40, 'cloverleaf Insurance ', NULL, NULL),
            (41, 'Legal & General ', NULL, NULL),
            (42, 'London Insurance ', NULL, NULL),
            (43, 'Loyalis ', NULL, NULL),
            (44, 'menzis ', NULL, NULL),
            (45, 'Mondial Assistance ', NULL, NULL),
            (46, 'MoneYou ', NULL, NULL),
            (47, 'Monuta ', NULL, NULL),
            (48, 'Movir ', NULL, NULL),
            (49, 'National Academic ', NULL, NULL),
            (50, 'Nationale Nederlanden ', NULL, NULL),
            (51, 'NIBC Direct ', NULL, NULL),
            (52, 'Noordhollandsche 1816 ', NULL, NULL),
            (53, 'Nuvema ', NULL, NULL),
            (54, 'Obvion ', NULL, NULL),
            (55, 'OHRA ', NULL, NULL),
            (56, 'OHRA Bank ', NULL, NULL),
            (57, 'Mutual Aid Insurance ', NULL, NULL),
            (58, 'Onna-Onna ', NULL, NULL),
            (59, 'ONVZ Zorgverzekeraar ', NULL, NULL),
            (60, 'OOM Insurance ', NULL, NULL),
            (61, 'Orion Direct ', NULL, NULL),
            (62, 'OZF Achmea ', NULL, NULL),
            (63, 'Paerel Life ', NULL, NULL),
            (64, 'PC Uitvaartzorg ', NULL, NULL),
            (65, 'PGGM ', NULL, NULL),
            (66, 'PNO ', NULL, NULL),
            (67, 'Polis Direct ', NULL, NULL),
            (68, 'Prolife ', NULL, NULL),
            (69, 'Proteq Animal ', NULL, NULL),
            (70, 'Proteq Direct ', NULL, NULL),
            (71, 'PVF Achmea ', NULL, NULL),
            (72, 'PWZ Achmea ', NULL, NULL),
            (73, 'Queens ', NULL, NULL),
            (74, 'Rabobank ', NULL, NULL),
            (75, 'REAAL Insurance ', NULL, NULL),
            (76, 'Robeco Direct ', NULL, NULL),
            (77, 'Robein Bank ', NULL, NULL),
            (78, 'Robein Life ', NULL, NULL),
            (79, 'stainless Steel ', NULL, NULL),
            (80, 'salland insurance ', NULL, NULL),
            (81, 'Santander ', NULL, NULL),
            (82, 'Schretlen ', NULL, NULL),
            (83, 'SNS Bank ', NULL, NULL),
            (84, 'RegioBank ', NULL, NULL),
            (85, 'Staalbankiers ', NULL, NULL),
            (86, 'Holland City Health insurer ', NULL, NULL),
            (87, 'SZVK ', NULL, NULL),
            (88, 'TakeCareNow ', NULL, NULL),
            (89, 'TEB The Economy Bank ', NULL, NULL),
            (90, 'Trias Health Insurance ', NULL, NULL),
            (91, 'Triodos Bank ', NULL, NULL),
            (92, 'Turien ', NULL, NULL),
            (93, 'TVM Insurance ', NULL, NULL),
            (94, 'Unigarant ', NULL, NULL),
            (95, 'Unive Insurance ', NULL, NULL),
            (96, 'Van Lanschot Bankiers ', NULL, NULL),
            (97, 'VvAA ', NULL, NULL),
            (98, 'WestlandUtrecht Hypotheekbank ', NULL, NULL),
            (99, 'Residential Mortgage Fund ', NULL, NULL),
            (100, 'Silver Cross Achmea ', NULL, NULL),
            (101, 'ZLM Insurance ', NULL, NULL),
            (102, 'Care and Security ', NULL, NULL),
            (103, 'Health insurer DSW ', NULL, NULL),
            (104, 'Health insurer VGZ ', NULL, NULL),
            (105, 'Zwitserleven ', NULL, NULL);


            INSERT INTO `dropdown_load_box` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'box 1 ', NULL, NULL),
            (2, 'box 2 ', NULL, NULL),
            (3, 'box 3 ', NULL, NULL);



            INSERT INTO `dropdown_marital_status` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Married in community of property ', NULL, NULL),
            (2, 'Married to prenup ', NULL, NULL),
            (3, 'Married under foreign law ', NULL, NULL),
            (4, 'Partner Registration in community of property ', NULL, NULL),
            (5, 'Partner Registry under registration conditions ', NULL, NULL),
            (6, 'Living together with cohabitation ', NULL, NULL),
            (7, 'Living together without cohabitation ', NULL, NULL),
            (8, 'single ', NULL, NULL),
            (9, 'Single, widow / widower ', NULL, NULL),
            (10, 'Single, divorced ', NULL, NULL);

            INSERT INTO `dropdown_nations` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Afghanistan ', NULL, NULL),
            (2, 'Akrotiri ', NULL, NULL),
            (3, 'Albania ', NULL, NULL),
            (4, 'Algeria ', NULL, NULL),
            (5, 'U.S. Virgin Islands ', NULL, NULL),
            (6, 'American Samoa ', NULL, NULL),
            (7, 'Andorra ', NULL, NULL),
            (8, 'Angola ', NULL, NULL),
            (9, 'Anguilla ', NULL, NULL),
            (10, 'Antarctica ', NULL, NULL),
            (11, 'Antigua and Barbuda ', NULL, NULL),
            (12, 'Arctic Ocean ', NULL, NULL),
            (13, 'Argentina ', NULL, NULL),
            (14, 'Armenia ', NULL, NULL),
            (15, 'Aruba ', NULL, NULL),
            (16, 'Ashmore and Cartier Islands ', NULL, NULL),
            (17, 'Atlantic Ocean ', NULL, NULL),
            (18, 'Australia ', NULL, NULL),
            (19, 'Azerbaijan ', NULL, NULL),
            (20, 'Bahamas ', NULL, NULL),
            (21, 'Bahrain ', NULL, NULL),
            (22, 'Bangladesh ', NULL, NULL),
            (23, 'Barbados ', NULL, NULL),
            (24, 'Belarus ', NULL, NULL),
            (25, 'Belgium ', NULL, NULL),
            (26, 'Belize ', NULL, NULL),
            (27, 'Benin ', NULL, NULL),
            (28, 'Bermuda ', NULL, NULL),
            (29, 'Bhutan ', NULL, NULL),
            (30, 'Bolivia ', NULL, NULL),
            (31, 'Bosnia and Herzegovina ', NULL, NULL),
            (32, 'Botswana ', NULL, NULL),
            (33, 'Bouvet Island ', NULL, NULL),
            (34, 'Brazil ', NULL, NULL),
            (35, 'British Indian Ocean Territory ', NULL, NULL),
            (36, 'British Virgin Islands ', NULL, NULL),
            (37, 'Brunei ', NULL, NULL),
            (38, 'Bulgaria ', NULL, NULL),
            (39, 'Burkina Faso ', NULL, NULL),
            (40, 'Burundi ', NULL, NULL),
            (41, 'Cambodia ', NULL, NULL),
            (42, 'Canada ', NULL, NULL),
            (43, 'Cayman Islands ', NULL, NULL),
            (44, 'Central African Republic ', NULL, NULL),
            (45, 'Chile ', NULL, NULL),
            (46, 'China ', NULL, NULL),
            (47, 'Christmas Island ', NULL, NULL),
            (48, 'Clipperton Island ', NULL, NULL),
            (49, 'Cocos (Keeling) Islands ', NULL, NULL),
            (50, 'Colombia ', NULL, NULL),
            (51, 'Comoros (Union) ', NULL, NULL),
            (52, 'Congo (Democratic Republic) ', NULL, NULL),
            (53, 'Congo (People''s Republic) ', NULL, NULL),
            (54, 'Cook ', NULL, NULL),
            (55, 'Coral Sea Islands ', NULL, NULL),
            (56, 'Costa Rica ', NULL, NULL),
            (57, 'Cuba ', NULL, NULL),
            (58, 'Cyprus ', NULL, NULL),
            (59, 'Denmark ', NULL, NULL),
            (60, 'Dhekelia ', NULL, NULL),
            (61, 'Djibouti ', NULL, NULL),
            (62, 'Dominica ', NULL, NULL),
            (63, 'Dominican Republic ', NULL, NULL),
            (64, 'Germany ', NULL, NULL),
            (65, 'Ecuador ', NULL, NULL),
            (66, 'Egypt ', NULL, NULL),
            (67, 'El Salvador ', NULL, NULL),
            (68, 'Equatorial Guinea ', NULL, NULL),
            (69, 'Eritrea ', NULL, NULL),
            (70, 'Estonia ', NULL, NULL),
            (71, 'Ethiopia ', NULL, NULL),
            (72, 'European Union ', NULL, NULL),
            (73, 'Falkland ', NULL, NULL),
            (74, 'Faroe Islands ', NULL, NULL),
            (75, 'Fiji ', NULL, NULL),
            (76, 'Philippines ', NULL, NULL),
            (77, 'Finland ', NULL, NULL),
            (78, 'France ', NULL, NULL),
            (79, 'French Polynesia ', NULL, NULL),
            (80, 'French Southern and Antarctic Lands ', NULL, NULL),
            (81, 'Gabon ', NULL, NULL),
            (82, 'Gambia ', NULL, NULL),
            (83, 'Gaza Strip ', NULL, NULL),
            (84, 'Georgia ', NULL, NULL),
            (85, 'Ghana ', NULL, NULL),
            (86, 'Gibraltar ', NULL, NULL),
            (87, 'Grenada ', NULL, NULL),
            (88, 'Greece ', NULL, NULL),
            (89, 'Greenland ', NULL, NULL),
            (90, 'Guam ', NULL, NULL),
            (91, 'Guatemala ', NULL, NULL),
            (92, 'Guernsey ', NULL, NULL),
            (93, 'Guinea ', NULL, NULL),
            (94, 'Guinea-Bissau ', NULL, NULL),
            (95, 'Guyana ', NULL, NULL),
            (96, 'Haiti ', NULL, NULL),
            (97, 'Heard Island and McDonald Islands ', NULL, NULL),
            (98, 'Holy See ', NULL, NULL),
            (99, 'Honduras ', NULL, NULL),
            (100, 'Hungary ', NULL, NULL),
            (101, 'Hong Kong ', NULL, NULL),
            (102, 'Ireland ', NULL, NULL),
            (103, 'Iceland ', NULL, NULL),
            (104, 'India ', NULL, NULL),
            (105, 'Indian Ocean ', NULL, NULL),
            (106, 'Indonesia ', NULL, NULL),
            (107, 'Iraq ', NULL, NULL),
            (108, 'Iran ', NULL, NULL),
            (109, 'Isle of Man ', NULL, NULL),
            (110, 'Israel ', NULL, NULL),
            (111, 'Italy ', NULL, NULL),
            (112, 'ivory Coast ', NULL, NULL),
            (113, 'Jamaica ', NULL, NULL),
            (114, 'Jan Mayen ', NULL, NULL),
            (115, 'Japan ', NULL, NULL),
            (116, 'Yemen ', NULL, NULL),
            (117, 'Jersey ', NULL, NULL),
            (118, 'Jordan ', NULL, NULL),
            (119, 'Cape Verde ', NULL, NULL),
            (120, 'Cameroon ', NULL, NULL),
            (121, 'Kazakhstan ', NULL, NULL),
            (122, 'Kenya ', NULL, NULL),
            (123, 'Kyrgyzstan ', NULL, NULL),
            (124, 'Kiribati ', NULL, NULL),
            (125, 'Kuwait ', NULL, NULL),
            (126, 'Croatia ', NULL, NULL),
            (127, 'Laos ', NULL, NULL),
            (128, 'Lesotho ', NULL, NULL),
            (129, 'Latvia ', NULL, NULL),
            (130, 'Lebanon ', NULL, NULL),
            (131, 'Liberia ', NULL, NULL),
            (132, 'Libya ', NULL, NULL),
            (133, 'Liechtenstein ', NULL, NULL),
            (134, 'Lithuania ', NULL, NULL),
            (135, 'Luxembourg ', NULL, NULL),
            (136, 'Macao ', NULL, NULL),
            (137, 'Macedonia ', NULL, NULL),
            (138, 'Malagasy ', NULL, NULL),
            (139, 'Malawi ', NULL, NULL),
            (140, 'Maldives ', NULL, NULL),
            (141, 'Malaysia ', NULL, NULL),
            (142, 'Mali ', NULL, NULL),
            (143, 'Malta ', NULL, NULL),
            (144, 'Morocco ', NULL, NULL),
            (145, 'Marshall Islands ', NULL, NULL),
            (146, 'Mauritania ', NULL, NULL),
            (147, 'Mauritius ', NULL, NULL),
            (148, 'Mayotte ', NULL, NULL),
            (149, 'Mexico ', NULL, NULL),
            (150, 'Micronesia, Federated States of ', NULL, NULL),
            (151, 'Moldova ', NULL, NULL),
            (152, 'Monaco ', NULL, NULL),
            (153, 'Mongolia ', NULL, NULL),
            (154, 'Montenegro ', NULL, NULL),
            (155, 'Montserrat ', NULL, NULL),
            (156, 'Mozambique ', NULL, NULL),
            (157, 'Myanmar ', NULL, NULL),
            (158, 'Namibia ', NULL, NULL),
            (159, 'Nauru ', NULL, NULL),
            (160, 'Navassa Island ', NULL, NULL),
            (161, 'Netherlands ', NULL, NULL),
            (162, 'Netherlands Antilles ', NULL, NULL),
            (163, 'Nepal ', NULL, NULL),
            (164, 'Ngwane ', NULL, NULL),
            (165, 'Nicaragua ', NULL, NULL),
            (166, 'New Caledonia ', NULL, NULL),
            (167, 'New Zealand ', NULL, NULL),
            (168, 'Niger ', NULL, NULL),
            (169, 'Nigeria ', NULL, NULL),
            (170, 'Niue ', NULL, NULL),
            (171, 'northern Mariana Islands ', NULL, NULL),
            (172, 'North Korea ', NULL, NULL),
            (173, 'Norway ', NULL, NULL),
            (174, 'Norfolk Island ', NULL, NULL),
            (175, 'Ukraine ', NULL, NULL),
            (176, 'Uzbekistan ', NULL, NULL),
            (177, 'Oman ', NULL, NULL),
            (178, 'Austria ', NULL, NULL),
            (179, 'Pacific Ocean ', NULL, NULL),
            (180, 'Pakistan ', NULL, NULL),
            (181, 'Palau ', NULL, NULL),
            (182, 'Panama ', NULL, NULL),
            (183, 'Papua New Guinea ', NULL, NULL),
            (184, 'Paracel Islands ', NULL, NULL),
            (185, 'Paraguay ', NULL, NULL),
            (186, 'Peru ', NULL, NULL),
            (187, 'Pitcairn ', NULL, NULL),
            (188, 'Poland ', NULL, NULL),
            (189, 'Portugal ', NULL, NULL),
            (190, 'Puerto Rico ', NULL, NULL),
            (191, 'Qatar ', NULL, NULL),
            (192, 'Romania ', NULL, NULL),
            (193, 'Russia ', NULL, NULL),
            (194, 'Rwanda ', NULL, NULL),
            (195, 'Saint Helena ', NULL, NULL),
            (196, 'Saint Lucia ', NULL, NULL),
            (197, 'Saint Vincent and the Grenadines ', NULL, NULL),
            (198, 'Saint-Pierre and Miquelon ', NULL, NULL),
            (199, 'Salomon ', NULL, NULL),
            (200, 'Samoa ', NULL, NULL),
            (201, 'San Marino ', NULL, NULL),
            (202, 'Sao Tome and Principe ', NULL, NULL),
            (203, 'Saudi Arabia ', NULL, NULL),
            (204, 'Senegal ', NULL, NULL),
            (205, 'Serbia ', NULL, NULL),
            (206, 'Seychelles ', NULL, NULL),
            (207, 'Sierra Leone ', NULL, NULL),
            (208, 'Singapore ', NULL, NULL),
            (209, 'Saint Kitts and Nevis ', NULL, NULL),
            (210, 'Slovenia ', NULL, NULL),
            (211, 'Slovakia ', NULL, NULL),
            (212, 'Sudan ', NULL, NULL),
            (213, 'Somalia ', NULL, NULL),
            (214, 'South Georgia and South Sandwich Islands ', NULL, NULL),
            (215, 'Southern Ocean ', NULL, NULL),
            (216, 'Spain ', NULL, NULL),
            (217, 'Spratly Islands ', NULL, NULL),
            (218, 'Sri Lanka ', NULL, NULL),
            (219, 'Suriname ', NULL, NULL),
            (220, 'Svalbard ', NULL, NULL),
            (221, 'Syria ', NULL, NULL),
            (222, 'Tadjikistan ', NULL, NULL),
            (223, 'Taiwan ', NULL, NULL),
            (224, 'Tanzania ', NULL, NULL),
            (225, 'Thailand ', NULL, NULL),
            (226, 'Timor Leste ', NULL, NULL),
            (227, 'Togo ', NULL, NULL),
            (228, 'Tokelau ', NULL, NULL),
            (229, 'Tonga ', NULL, NULL),
            (230, 'Trinidad and Tobago ', NULL, NULL),
            (231, 'Chad ', NULL, NULL),
            (232, 'Czech Republic ', NULL, NULL),
            (233, 'Tunisia ', NULL, NULL),
            (234, 'Turkey ', NULL, NULL),
            (235, 'Turkmenistan ', NULL, NULL),
            (236, 'Turks and Caicos ', NULL, NULL),
            (237, 'Tuvalu ', NULL, NULL),
            (238, 'Uganda ', NULL, NULL),
            (239, 'Uruguay ', NULL, NULL),
            (240, 'Vanuatu ', NULL, NULL),
            (241, 'Venezuela ', NULL, NULL),
            (242, 'United Kingdom ', NULL, NULL),
            (243, 'United Arab Emirates ', NULL, NULL),
            (244, 'United States ', NULL, NULL),
            (245, 'Vietnam ', NULL, NULL),
            (246, 'Wake Island ', NULL, NULL),
            (247, 'Wallis and Futuna ', NULL, NULL),
            (248, 'world ', NULL, NULL),
            (249, 'West Bank ', NULL, NULL),
            (250, 'Western Sahara ', NULL, NULL),
            (251, 'Zambia ', NULL, NULL),
            (252, 'Zimbabwe ', NULL, NULL),
            (253, 'South Africa ', NULL, NULL),
            (254, 'South Korea ', NULL, NULL),
            (255, 'Sweden ', NULL, NULL),
            (256, 'Switzerland ', NULL, NULL);

            INSERT INTO `dropdown_payment` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'month ', NULL, NULL),
            (2, 'quarter ', NULL, NULL),
            (3, 'half year ', NULL, NULL),
            (4, 'year ', NULL, NULL);


            INSERT INTO `dropdown_pension_funds_and_pension_insurers` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Van Lanschot Bankiers ', NULL, NULL),
            (2, 'Interpolis ', NULL, NULL),
            (3, 'the Amersfoort ', NULL, NULL),
            (4, 'Delta Lloyd ', NULL, NULL),
            (5, 'Aegon ', NULL, NULL),
            (6, 'real ', NULL, NULL),
            (7, 'ASR Insurance ', NULL, NULL),
            (8, 'OHRA ', NULL, NULL),
            (9, 'stainless Steel ', NULL, NULL),
            (10, 'Nationale Nederlanden ', NULL, NULL),
            (11, 'ABN Amro ', NULL, NULL),
            (12, 'Paerel Life ', NULL, NULL),
            (13, 'mutual s''Gravenhage ', NULL, NULL),
            (14, 'Zwitserleven ', NULL, NULL),
            (15, 'Theodoor Gilissen ', NULL, NULL),
            (16, 'The Gouda Insurance ', NULL, NULL),
            (17, 'Legal & General ', NULL, NULL),
            (18, 'national Savings Fund ', NULL, NULL),
            (19, 'Agricultural and Food ', NULL, NULL),
            (20, 'Pharmacies ', NULL, NULL),
            (21, 'Architect ', NULL, NULL),
            (22, 'doctors ', NULL, NULL),
            (23, 'dredging Companies ', NULL, NULL),
            (24, 'bakery ', NULL, NULL),
            (25, 'Tire and wheel industry ', NULL, NULL),
            (26, 'Occupation Road transport ', NULL, NULL),
            (27, 'Library, public ', NULL, NULL),
            (28, 'building retirement ', NULL, NULL),
            (29, 'construction UTA ', NULL, NULL),
            (30, 'Building Materials Trade ', NULL, NULL),
            (31, 'retail ', NULL, NULL),
            (32, 'Film and cinema business ', NULL, NULL),
            (33, 'physiotherapists ', NULL, NULL),
            (34, 'mental health ', NULL, NULL),
            (35, 'printing companies ', NULL, NULL),
            (36, 'Fruit and Vegetable Processing ', NULL, NULL),
            (37, 'Catering ', NULL, NULL),
            (38, 'timber trade ', NULL, NULL),
            (39, 'Cardboard and Packaging ', NULL, NULL),
            (40, 'prolonged Temporary workers ', NULL, NULL),
            (41, 'Media / PNO ', NULL, NULL),
            (42, 'Metal & Technology ', NULL, NULL),
            (43, 'Metallurgy ', NULL, NULL),
            (44, 'Metalektro pension ', NULL, NULL),
            (45, 'Furniture and Meubileringsbedrijven ', NULL, NULL),
            (46, 'natural ', NULL, NULL),
            (47, 'Government and Education (ABP) ', NULL, NULL),
            (48, 'Government privatized ', NULL, NULL),
            (49, 'Government, Netherlands Antilles ', NULL, NULL),
            (50, 'Commodity ', NULL, NULL),
            (51, 'Relan (retail like) ', NULL, NULL),
            (52, 'Shipbuilding (Poseidon) ', NULL, NULL),
            (53, 'Painters / Finishing / Glaszet ', NULL, NULL),
            (54, 'Sportfondsen ', NULL, NULL),
            (55, 'Plasterers / dismantling / floors ', NULL, NULL),
            (56, 'Sugar Manufacturing Industry ', NULL, NULL),
            (57, 'Dentists ', NULL, NULL),
            (58, 'technical wholesale ', NULL, NULL),
            (59, 'Theatre, Dance, Arts & Culture ', NULL, NULL),
            (60, 'funeral ', NULL, NULL),
            (61, 'Stay tourism ', NULL, NULL),
            (62, 'paint ', NULL, NULL),
            (63, 'Transport, Professional road ', NULL, NULL),
            (64, 'Transport, Public ', NULL, NULL),
            (65, 'Transport, Railways ', NULL, NULL),
            (66, 'Meat and Meat Products ', NULL, NULL),
            (67, 'Civil engineering ', NULL, NULL),
            (68, 'Work & (re) integration ', NULL, NULL),
            (69, 'housing associations ', NULL, NULL),
            (70, 'Care, nursing (PGGM) ', NULL, NULL),
            (71, 'Health Insurers ', NULL, NULL),
            (72, 'C & A ', NULL, NULL),
            (73, 'DSM ', NULL, NULL),
            (74, 'Elsevier Businesses ', NULL, NULL),
            (75, 'FNV ', NULL, NULL),
            (76, 'Hoogovens (Corus) ', NULL, NULL),
            (77, 'IBM ', NULL, NULL),
            (78, 'ING ', NULL, NULL),
            (79, 'Internatio-Müller ', NULL, NULL),
            (80, 'KLM, general (ground) ', NULL, NULL),
            (81, 'KLM cabin crew ', NULL, NULL),
            (82, 'KLM, aircrew ', NULL, NULL),
            (83, 'KPN pension site ', NULL, NULL),
            (84, 'MSD ', NULL, NULL),
            (85, 'Nedlloyd ', NULL, NULL),
            (86, 'Philips Pension Fund ', NULL, NULL),
            (87, 'Rabobank ', NULL, NULL),
            (88, 'rail transport ', NULL, NULL),
            (89, 'Shell pension fund management ', NULL, NULL),
            (90, 'Stork ', NULL, NULL),
            (91, 'TDV ', NULL, NULL),
            (92, 'TNO ', NULL, NULL),
            (93, 'Total ', NULL, NULL),
            (94, 'TPG retire site ', NULL, NULL),
            (95, 'Vendex KBB ', NULL, NULL),
            (96, 'Volker Wessels Stevin ', NULL, NULL),
            (97, 'Wolters Kluwer-', NULL, NULL);


            INSERT INTO `dropdown_period_salary` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'month ', NULL, NULL),
            (2, '4 weeks ', NULL, NULL),
            (3, 'week ', NULL, NULL);


            INSERT INTO `dropdown_property_type` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'apartment ', NULL, NULL),
            (2, 'Apartment with garage ', NULL, NULL),
            (3, 'ranch ', NULL, NULL),
            (4, 'family house ', NULL, NULL),
            (5, 'Family house with garage ', NULL, NULL),
            (6, 'Holiday ', NULL, NULL),
            (7, 'Two under 1 roof ', NULL, NULL),
            (8, 'detached house ', NULL, NULL),
            (9, 'Shop - house ', NULL, NULL),
            (10, 'House with commercial space ', NULL, NULL);


            INSERT INTO `dropdown_repayment_rortgage_rorm` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Interest only ', NULL, NULL),
            (2, 'Annuity ', NULL, NULL),
            (3, 'Bank savings ', NULL, NULL),
            (4, 'invest ', NULL, NULL),
            (5, 'hybrid ', NULL, NULL),
            (6, 'credit ', NULL, NULL),
            (7, 'life ', NULL, NULL),
            (8, 'linear ', NULL, NULL),
            (9, 'savings ', NULL, NULL);


            INSERT INTO `dropdown_status_damages` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'insurance claim received ', NULL, NULL),
            (2, 'Damage treatment ', NULL, NULL),
            (3, 'damage rejected ', NULL, NULL),
            (4, 'damages paid ', NULL, NULL);


            INSERT INTO `dropdown_subscriptions` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Service with discount ', NULL, NULL),
            (2, 'service ', NULL, NULL),
            (3, 'Service Partner, child ', NULL, NULL),
            (4, 'resident service ', NULL, NULL),
            (5, 'Service charge ', NULL, NULL),
            (6, 'student service ', NULL, NULL),
            (7, 'service basis ', NULL, NULL),
            (8, 'service recreation ', NULL, NULL);


            INSERT INTO `dropdown_type_of_benefit` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'AO ', NULL, NULL),
            (2, 'WW ', NULL, NULL),
            (3, 'annuity ', NULL, NULL),
            (4, 'assistance ', NULL, NULL);


            INSERT INTO `dropdown_type_of_coverage_by_insurance` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'single coverage ', NULL, NULL),
            (2, 'Family Coverage ', NULL, NULL),
            (3, 'cancellation ', NULL, NULL),
            (4, 'Up to € 1500, - per person ', NULL, NULL),
            (5, 'Up to € 3000, - per person ', NULL, NULL),
            (6, 'Up to € 4500, - per person ', NULL, NULL),
            (7, 'Actual costs ', NULL, NULL),
            (8, 'suitable work ', NULL, NULL),
            (9, 'Common labor ', NULL, NULL),
            (10, 'Occupation Labour unfitness ', NULL, NULL),
            (11, 'All risk ', NULL, NULL),
            (12, 'All risk oi + ', NULL, NULL),
            (13, 'All risk + si ', NULL, NULL),
            (14, 'All risk + rb ', NULL, NULL),
            (15, 'All risk + bonus protector ', NULL, NULL),
            (16, 'All risk oi + + rb ', NULL, NULL),
            (17, 'All risk si + + rb ', NULL, NULL),
            (18, 'All risk oi + bonus + protector ', NULL, NULL),
            (19, 'All risk si + + bonus protector ', NULL, NULL),
            (20, 'All risk + rb + bonus protector ', NULL, NULL),
            (21, 'All risk oi + + rb + bonus protector ', NULL, NULL),
            (22, 'All risk si + + rb + bonus protector ', NULL, NULL),
            (23, 'WA limited airframe ', NULL, NULL),
            (24, 'WA limited airframe + oi ', NULL, NULL),
            (25, 'WA limited airframe + si ', NULL, NULL),
            (26, 'WA limited airframe + rb ', NULL, NULL),
            (27, 'WA limited airframe + bonus protector ', NULL, NULL),
            (28, 'WA limited airframe + oi + rb ', NULL, NULL),
            (29, 'WA limited airframe si + + rb ', NULL, NULL),
            (30, 'WA limited airframe + oi + bonus protector ', NULL, NULL),
            (31, 'WA limited airframe + Si + bonus protector ', NULL, NULL),
            (32, 'WA limited airframe + rb + bonus protector ', NULL, NULL),
            (33, 'WA limited airframe + oi + rb + bonus protector ', NULL, NULL),
            (34, 'WA limited airframe + Si + rb + bonus protector ', NULL, NULL),
            (35, 'WA ', NULL, NULL),
            (36, 'WA + oi ', NULL, NULL),
            (37, 'WA + si ', NULL, NULL),
            (38, 'WA + rb ', NULL, NULL),
            (39, 'WA + bonus protector ', NULL, NULL),
            (40, 'WA + oi + rb ', NULL, NULL),
            (41, 'WA si + + rb ', NULL, NULL),
            (42, 'WA + oi + bonus protector ', NULL, NULL),
            (43, 'WA + si + bonus protector ', NULL, NULL),
            (44, 'WA + rb + bonus protector ', NULL, NULL),
            (45, 'WA + oi + rb + bonus protector ', NULL, NULL),
            (46, 'WA si + + rb + bonus protector ', NULL, NULL),
            (47, 'business Liability Insurance ', NULL, NULL),
            (48, 'extensive ', NULL, NULL),
            (49, 'Advanced + Glass ', NULL, NULL),
            (50, 'additional extended ', NULL, NULL),
            (51, 'Extra wide glass + ', NULL, NULL),
            (52, 'extensive ', NULL, NULL),
            (53, 'additional extended ', NULL, NULL),
            (54, 'investment insurance ', NULL, NULL),
            (55, 'professional Liability Insurance ', NULL, NULL),
            (56, 'All risk ', NULL, NULL),
            (57, 'All risk oi + ', NULL, NULL),
            (58, 'All risk + si ', NULL, NULL),
            (59, 'All risk + rb ', NULL, NULL),
            (60, 'All risk oi + + rb ', NULL, NULL),
            (61, 'All risk si + + rb ', NULL, NULL),
            (62, 'WA limited airframe ', NULL, NULL),
            (63, 'WA limited airframe + oi ', NULL, NULL),
            (64, 'WA limited airframe + si ', NULL, NULL),
            (65, 'WA limited airframe + rb ', NULL, NULL),
            (66, 'WA limited airframe + oi + rb ', NULL, NULL),
            (67, 'WA limited airframe si + + rb ', NULL, NULL),
            (68, 'WA ', NULL, NULL),
            (69, 'WA + oi ', NULL, NULL),
            (70, 'WA + si ', NULL, NULL),
            (71, 'WA + rb ', NULL, NULL),
            (72, 'WA + oi + rb ', NULL, NULL),
            (73, 'WA si + + rb ', NULL, NULL),
            (74, 'All risk ', NULL, NULL),
            (75, '#NAME?', NULL, NULL),
            (76, 'All risks of accidents opzittende + + rb ', NULL, NULL),
            (77, 'All risk + rb ', NULL, NULL),
            (78, 'WA limited airframe ', NULL, NULL),
            (79, 'WA limited airframe + accidents opzittende ', NULL, NULL),
            (80, 'WA limited airframe + accident + rb opzittende ', NULL, NULL),
            (81, 'WA limited airframe + rb ', NULL, NULL),
            (82, 'WA ', NULL, NULL),
            (83, 'WA + accidents opzittende ', NULL, NULL),
            (84, 'WA + accident + rb opzittende ', NULL, NULL),
            (85, 'WA + rb ', NULL, NULL),
            (86, 'standard ', NULL, NULL),
            (87, 'bespoke ', NULL, NULL),
            (88, 'All risk ', NULL, NULL),
            (89, 'WA limited airframe ', NULL, NULL),
            (90, 'WA ', NULL, NULL),
            (91, '1. Discontinue ', NULL, NULL),
            (92, '2. Absence of people + 1 ', NULL, NULL),
            (93, '3. Liability + 1 and 2 ', NULL, NULL),
            (94, '4. Accidents + 1,2, and 3 ', NULL, NULL),
            (95, '5. Rain + 1,2,3, and 4 ', NULL, NULL),
            (96, '6. + Object 1,2,3,4, and 5 ', NULL, NULL),
            (97, 'Current ', NULL, NULL),
            (98, 'continuously ', NULL, NULL),
            (99, 'garage Insurance ', NULL, NULL),
            (100, 'Damage and theft ', NULL, NULL),
            (101, 'standard ', NULL, NULL),
            (102, 'hybrid Insurance ', NULL, NULL),
            (103, 'extensive ', NULL, NULL),
            (104, 'additional extended ', NULL, NULL),
            (105, 'All risk ', NULL, NULL),
            (106, 'Advanced + Glass ', NULL, NULL),
            (107, 'Extra wide glass + ', NULL, NULL),
            (108, 'All risk + glass ', NULL, NULL),
            (109, 'Fire, explosion and lightning (PDO) ', NULL, NULL),
            (110, 'BOB + aircraft damage and storm damage ', NULL, NULL),
            (111, 'extensive ', NULL, NULL),
            (112, 'BOB + glass ', NULL, NULL),
            (113, 'BOB + Aircraft Damage and storm damage + glass ', NULL, NULL),
            (114, 'Advanced + Glass ', NULL, NULL),
            (115, 'All risk ', NULL, NULL),
            (116, 'All risk + glass ', NULL, NULL),
            (117, 'All risk ', NULL, NULL),
            (118, 'All risk oi + ', NULL, NULL),
            (119, 'All risk + si ', NULL, NULL),
            (120, 'All risk + rb ', NULL, NULL),
            (121, 'All risks + possessions ', NULL, NULL),
            (122, 'All risk oi + + rb ', NULL, NULL),
            (123, 'All risk si + + rb ', NULL, NULL),
            (124, 'All risk oi + + contents ', NULL, NULL),
            (125, 'All risk si + + contents ', NULL, NULL),
            (126, 'All risk rb + + contents ', NULL, NULL),
            (127, 'All risk oi + + + rb contents ', NULL, NULL),
            (128, 'All risk si + + rb + contents ', NULL, NULL),
            (129, 'WA limited airframe ', NULL, NULL),
            (130, 'WA limited airframe + oi ', NULL, NULL),
            (131, 'WA limited airframe + si ', NULL, NULL),
            (132, 'WA limited airframe + rb ', NULL, NULL),
            (133, 'WA limited airframe + contents ', NULL, NULL),
            (134, 'WA limited airframe + oi + rb ', NULL, NULL),
            (135, 'WA limited airframe si + + rb ', NULL, NULL),
            (136, 'WA limited airframe + oi + contents ', NULL, NULL),
            (137, 'WA limited airframe si + + contents ', NULL, NULL),
            (138, 'WA limited airframe + rb + contents ', NULL, NULL),
            (139, 'WA limited airframe + oi + rb + contents ', NULL, NULL),
            (140, 'WA limited airframe + j + + rb contents ', NULL, NULL),
            (141, 'WA ', NULL, NULL),
            (142, 'WA + oi ', NULL, NULL),
            (143, 'WA + si ', NULL, NULL),
            (144, 'WA + rb ', NULL, NULL),
            (145, 'WA + contents ', NULL, NULL),
            (146, 'WA + oi + rb ', NULL, NULL),
            (147, 'WA si + + rb ', NULL, NULL),
            (148, 'WA + oi + contents ', NULL, NULL),
            (149, 'WA si + + contents ', NULL, NULL),
            (150, 'WA + rb + contents ', NULL, NULL),
            (151, 'WA oi + + + rb contents ', NULL, NULL),
            (152, 'WA si + + rb + contents ', NULL, NULL),
            (153, 'endowment ', NULL, NULL),
            (154, 'valuables Coverage ', NULL, NULL),
            (155, 'Mixed policy, one life ', NULL, NULL),
            (156, 'Mixed policy, two lives ', NULL, NULL),
            (157, 'fixed term ', NULL, NULL),
            (158, 'Policy with refund ', NULL, NULL),
            (159, 'Directly entering temporary, one life insurance policy ', NULL, NULL),
            (160, 'Directly entering temporary, two lives, policy ', NULL, NULL),
            (161, 'Directly entering life, one life insurance policy ', NULL, NULL),
            (162, 'Directly entering life, two lives, policy ', NULL, NULL),
            (163, 'Deferred annuity, policy ', NULL, NULL),
            (164, 'Directly entering temporary, one life, bank savings ', NULL, NULL),
            (165, 'Directly entering temporary, two lives, bank savings ', NULL, NULL),
            (166, 'Directly entering life, one life, bank savings ', NULL, NULL),
            (167, 'Directly entering life, two lives, bank savings ', NULL, NULL),
            (168, 'Deferred annuity, bank savings ', NULL, NULL),
            (169, 'WA ', NULL, NULL),
            (170, 'All risk ', NULL, NULL),
            (171, 'WA ', NULL, NULL),
            (172, 'WA limited airframe ', NULL, NULL),
            (173, 'All risk ', NULL, NULL),
            (174, 'All risk ', NULL, NULL),
            (175, 'All risk ', NULL, NULL),
            (176, '#NAME?', NULL, NULL),
            (177, 'All risks of accidents opzittende + + rb ', NULL, NULL),
            (178, 'All risk + rb ', NULL, NULL),
            (179, 'WA limited airframe ', NULL, NULL),
            (180, 'WA limited airframe + accidents opzittende ', NULL, NULL),
            (181, 'WA limited airframe + accident + rb opzittende ', NULL, NULL),
            (182, 'WA limited airframe + rb ', NULL, NULL),
            (183, 'WA ', NULL, NULL),
            (184, 'WA + accidents opzittende ', NULL, NULL),
            (185, 'WA + accident + rb opzittende ', NULL, NULL),
            (186, 'WA + rb ', NULL, NULL),
            (187, 'All risk ', NULL, NULL),
            (188, '#NAME?', NULL, NULL),
            (189, 'All risks of accidents opzittende + + rb ', NULL, NULL),
            (190, 'All risk + rb ', NULL, NULL),
            (191, 'WA limited airframe ', NULL, NULL),
            (192, 'WA limited airframe + accidents opzittende ', NULL, NULL),
            (193, 'WA limited airframe + accident + rb opzittende ', NULL, NULL),
            (194, 'WA limited airframe + rb ', NULL, NULL),
            (195, 'WA ', NULL, NULL),
            (196, 'WA + accidents opzittende ', NULL, NULL),
            (197, 'WA + accident + rb opzittende ', NULL, NULL),
            (198, 'WA + rb ', NULL, NULL),
            (199, 'single ', NULL, NULL),
            (200, 'Single with children ', NULL, NULL),
            (201, 'family ', NULL, NULL),
            (202, 'Family with children ', NULL, NULL),
            (203, 'extensive ', NULL, NULL),
            (204, 'additional extended ', NULL, NULL),
            (205, 'All risk ', NULL, NULL),
            (206, 'Advanced + Glass ', NULL, NULL),
            (207, 'Extra wide glass + ', NULL, NULL),
            (208, 'All risk + glass ', NULL, NULL),
            (209, 'Consistently one life ', NULL, NULL),
            (210, 'Consistently 2 lives ', NULL, NULL),
            (211, 'Annuity falling, one life ', NULL, NULL),
            (212, 'Annuity falling, two lives ', NULL, NULL),
            (213, 'Decreasing linearly, one life ', NULL, NULL),
            (214, 'Decreasing linearly, two lives ', NULL, NULL),
            (215, 'In case of death ', NULL, NULL),
            (216, 'In case of death + accident ', NULL, NULL),
            (217, 'extensive ', NULL, NULL),
            (218, 'packet ', NULL, NULL),
            (219, 'WA ', NULL, NULL),
            (220, 'WA + fire ', NULL, NULL),
            (221, 'WA + theft ', NULL, NULL),
            (222, 'WA + fire and theft ', NULL, NULL),
            (223, 'All risk ', NULL, NULL),
            (224, '1. Traffic ', NULL, NULL),
            (225, '2. Consumer and live + 1 ', NULL, NULL),
            (226, '3. Income + 1 and 2 ', NULL, NULL),
            (227, '4. Fiscal and power + 1,2 and 3 ', NULL, NULL),
            (228, '5. Mediation in divorce + 1, 2,3 and 4 ', NULL, NULL),
            (229, 'luggage ', NULL, NULL),
            (230, '#NAME?', NULL, NULL),
            (231, 'Baggage + accident ', NULL, NULL),
            (232, 'Baggage + dangerous sports ', NULL, NULL),
            (233, 'Baggage + money ', NULL, NULL),
            (234, 'Baggage + Cancellation ', NULL, NULL),
            (235, 'combination ', NULL, NULL),
            (236, 'luggage ', NULL, NULL),
            (237, '#NAME?', NULL, NULL),
            (238, 'Baggage + accident ', NULL, NULL),
            (239, 'Baggage + dangerous sports ', NULL, NULL),
            (240, 'Baggage + money ', NULL, NULL),
            (241, 'Baggage + Cancellation ', NULL, NULL),
            (242, 'combination ', NULL, NULL),
            (243, '1 person coverage in cash ', NULL, NULL),
            (244, 'Family Coverage in cash ', NULL, NULL),
            (245, '1 person coverage in kind ', NULL, NULL),
            (246, 'Family coverage in kind ', NULL, NULL),
            (247, 'All risk ', NULL, NULL),
            (248, 'All risk oi + ', NULL, NULL),
            (249, 'All risk + si ', NULL, NULL),
            (250, 'All risk + rb ', NULL, NULL),
            (251, 'All risk oi + + rb ', NULL, NULL),
            (252, 'All risk si + + rb ', NULL, NULL),
            (253, 'WA limited airframe ', NULL, NULL),
            (254, 'WA limited airframe + oi ', NULL, NULL),
            (255, 'WA limited airframe + si ', NULL, NULL),
            (256, 'WA limited airframe + rb ', NULL, NULL),
            (257, 'WA limited airframe + oi + rb ', NULL, NULL),
            (258, 'WA limited airframe si + + rb ', NULL, NULL),
            (259, 'WA ', NULL, NULL),
            (260, 'WA + oi ', NULL, NULL),
            (261, 'WA + si ', NULL, NULL),
            (262, 'WA + rb ', NULL, NULL),
            (263, 'WA + oi + rb ', NULL, NULL),
            (264, 'WA si + + rb ', NULL, NULL),
            (265, 'fleet Coverage ', NULL, NULL),
            (266, 'basis ', NULL, NULL),
            (267, 'Basic + transport ', NULL, NULL),
            (268, 'Base + live / work ', NULL, NULL),
            (269, 'Basic + transport + live / work ', NULL, NULL),
            (270, 'Damage and theft ', NULL, NULL),
            (271, 'conventional ', NULL, NULL),
            (272, 'stoploss ', NULL, NULL);


            INSERT INTO `dropdown_type_of_employment` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Employed full time permanent contract ', NULL, NULL),
            (2, 'Employed full time temporary contract ', NULL, NULL),
            (3, 'Employed part-time permanent contract ', NULL, NULL),
            (4, 'Employed part-time temporary contract ', NULL, NULL),
            (5, 'Director shareholder (DGA) ', NULL, NULL),
            (6, 'independent ', NULL, NULL),
            (7, 'Early retirement / pension ', NULL, NULL),
            (8, 'social benefits ', NULL, NULL),
            (9, 'no employment ', NULL, NULL);


            INSERT INTO `dropdown_type_of_health_insurance` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'basis ', NULL, NULL),
            (2, 'Base + additional coverage ', NULL, NULL),
            (3, 'Base + dentist ', NULL, NULL),
            (4, 'Base + additional + dental coverage ', NULL, NULL);


            INSERT INTO `dropdown_type_of_insurance` (`id`, `name`, `create_date`, `update_date`, `extra_information_type`,`created_by`,`update_by`,`language`) VALUES
            ('1', 'Liability ', null, '2014-07-23 12:49:26', '3', null, '1', 'En'),
            ('2', 'Cancellation (current) ', null, '2014-07-23 12:49:49', '3', null, '1', 'En'),
            ('3', 'Cancellation (continuous) ', null, '2014-07-23 12:50:12', '3', null, '1', 'En'),
            ('4', 'Car Insurance ', null, '2014-07-23 12:50:46', '1', null, '1', 'En'),
            ('5', 'business Liability Insurance ', null, '2014-07-23 12:53:22', '3', null, '1', 'En'),
            ('6', 'commercial buildings insurance ', null, '2014-07-23 12:53:37', '2', null, '1', 'En'),
            ('7', 'business Interruption ', null, '2014-07-23 12:53:50', '3', null, '1', 'En'),
            ('8', 'investment insurance ', null, '2014-07-23 12:54:00', '3', null, '1', 'En'),
            ('9', 'professional Liability Insurance ', null, '2014-07-23 12:54:11', '3', null, '1', 'En'),
            ('10', 'moped Insurance ', null, '2014-07-23 12:54:28', '1', null, '1', 'En'),
            ('11', 'CAR insurance ', null, '2014-07-23 12:54:37', '1', null, '1', 'En'),
            ('12', 'Caravan Insurance ', null, '2014-07-23 12:55:09', '1', null, '1', 'En'),
            ('13', 'Event Insurance ', null, '2014-07-23 12:55:16', '3', null, '1', 'En'),
            ('14', 'Gulf Insurance ', null, '2014-07-23 12:55:21', '3', null, '1', 'En'),
            ('15', 'dog Insurance ', null, '2014-07-23 12:55:35', '2', null, '1', 'En'),
            ('16', 'hybrid Insurance ', null, '2014-07-23 13:02:34', '3', null, '1', 'En'),
            ('17', 'contents insurance ', null, '2014-07-23 13:02:43', '3', null, '1', 'En'),
            ('18', 'inventory Insurance ', null, '2014-07-23 13:02:51', '3', null, '1', 'En'),
            ('19', 'camper Insurance ', null, '2014-07-23 13:02:57', '1', null, '1', 'En'),
            ('20', 'valuables Insurance ', null, '2014-07-23 13:03:02', '2', null, '1', 'En'),
            ('21', 'life insurance ', null, '2014-07-23 13:03:27', '3', null, '1', 'En'),
            ('22', 'aircraft Insurance ', null, '2014-07-23 13:03:31', '1', null, '1', 'En'),
            ('23', 'material Insurance ', null, '2014-07-23 13:03:36', '2', null, '1', 'En'),
            ('24', 'motor Insurance ', null, '2014-07-23 13:03:39', '1', null, '1', 'En'),
            ('25', 'Classic Car Insurance ', null, '2014-07-23 13:03:42', '1', null, '1', 'En'),
            ('26', 'accident ', null, '2014-07-23 13:03:46', '3', null, '1', 'En'),
            ('27', 'Home insurance ', null, '2014-07-23 13:03:50', '2', null, '1', 'En'),
            ('28', 'Term Life Insurance ', null, '2014-07-23 13:03:55', '3', null, '1', 'En'),
            ('29', 'horse Insurance ', null, '2014-07-23 13:03:59', '2', null, '1', 'En'),
            ('30', 'package Insurance ', null, '2014-07-23 13:04:04', '3', null, '1', 'En'),
            ('31', 'Recreational Boat Insurance ', null, '2014-07-23 13:04:34', '1', null, '1', 'En'),
            ('32', 'legal expenses ', null, '2014-07-23 13:04:38', '3', null, '1', 'En'),
            ('33', 'Travel insurance (current) ', null, '2014-07-23 13:04:43', '3', null, '1', 'En'),
            ('34', 'Travel insurance (continuous) ', null, '2014-07-23 13:04:47', '3', null, '1', 'En'),
            ('35', 'funeral ', null, '2014-07-23 13:04:51', '2', null, '1', 'En'),
            ('36', 'fleet Insurance ', null, '2014-07-23 13:05:28', '3', null, '1', 'En'),
            ('37', 'WEGAM insurance ', null, '2014-07-23 13:05:32', '3', null, '1', 'En'),
            ('38', 'WGA insurance ', null, '2014-07-23 13:05:36', '3', null, '1', 'En'),
            ('39', 'WIA insurance ', null, '2014-07-23 13:05:39', '3', null, '1', 'En'),
            ('40', 'Sailboard Insurance ', null, '2014-07-23 13:05:44', '1', null, '1', 'En'),
            ('41', 'absenteeism Insurance ', null, '2014-07-23 13:06:11', '3', null, '1', 'En'),
            ('42', 'Health Insurance ', null, '2014-07-23 13:06:16', '3', null, '1', 'En');


            INSERT INTO `dropdown_type_of_loan` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Credit card with credit ', NULL, NULL),
            (2, 'Credit card with no credit ', NULL, NULL),
            (3, 'personal loan ', NULL, NULL),
            (4, 'Revolving credit ', NULL, NULL),
            (5, 'lease ', NULL, NULL);


            INSERT INTO `dropdown_type_of_loans` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Revolving credit ', NULL, NULL),
            (2, 'personal loan ', NULL, NULL),
            (3, 'red Stand ', NULL, NULL),
            (4, 'flash Credit ', NULL, NULL),
            (5, 'Hire purchase ', NULL, NULL),
            (6, 'mail order ', NULL, NULL),
            (7, 'customer Cards ', NULL, NULL),
            (8, 'credit Cards ', NULL, NULL),
            (9, 'lease ', NULL, NULL),
            (10, 'Borrow against collateral ', NULL, NULL),
            (11, 'mortgages ', NULL, NULL);


            INSERT INTO `dropdown_type_of_maintenance` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'partner allimentatie ', NULL, NULL),
            (2, 'children allimentatie ', NULL, NULL);


            INSERT INTO `dropdown_type_of_mortgage` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Interest only mortgage ', NULL, NULL),
            (2, 'Bank savings mortgage ', NULL, NULL),
            (3, 'endowment ', NULL, NULL),
            (4, 'mortgage life Insurance ', NULL, NULL),
            (5, 'investment-', NULL, NULL),
            (6, 'Mortgage securities ', NULL, NULL),
            (7, 'Startershypotheek ', NULL, NULL),
            (8, 'hybrid mortgage ', NULL, NULL),
            (9, 'second mortgage ', NULL, NULL),
            (10, 'credit mortgage ', NULL, NULL);


            INSERT INTO `dropdown_type_of_retirement` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'available premium ', NULL, NULL),
            (2, 'Final salary ', NULL, NULL),
            (3, 'Average pay ', NULL, NULL),
            (4, 'Survivor''s pension ', NULL, NULL),
            (5, 'Orphan''s pension ', NULL, NULL),
            (6, 'purchase money ', NULL, NULL),
            (7, 'annuity ', NULL, NULL),
            (8, 'Immediate annuity ', NULL, NULL),
            (9, 'incapacity Annuity ', NULL, NULL);


            INSERT INTO `dropdown_ww_type_insurance` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Disability Insurance ', NULL, NULL),
            (2, 'unemployment Insurance ', NULL, NULL),
            (3, 'AO / unemployment insurance ', NULL, NULL);
            INSERT INTO `dropdown_role` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'Admin ', NULL, NULL, 'En'),
            (2, 'Employee Manager ', NULL, NULL, 'En'),
            (3, 'Employee ', NULL, NULL, 'En'),
            (4, 'intern ', NULL, NULL, 'En');

            INSERT INTO `dropdown_type` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'mortgages ', NULL, NULL, 'En'),
            (2, 'insurance ', NULL, NULL, 'En'),
            (3, 'pensions ', NULL, NULL, 'En'),
            (4, 'credits ', NULL, NULL, 'En'),
            (5, 'general ', NULL, NULL, 'En');

            INSERT INTO `dropdown_type_advice` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'mortgages ', NULL, NULL, 'En'),
            (2, 'insurance ', NULL, NULL, 'En'),
            (3, 'pensions ', NULL, NULL, 'En'),
            (4, 'credits ', NULL, NULL, 'En'),
            (5, 'general ', NULL, NULL, 'En');

            INSERT INTO `dropdown_bkr_code` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'A ', NULL, NULL, 'En'),
            (2, 'B ', NULL, NULL, 'En'),
            (3, 'C ', NULL, NULL, 'En');

            INSERT INTO `dropdown_type_of_customer` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, '0-18 years ', NULL, NULL, 'En'),
            (2, '18-25 years ', NULL, NULL, 'En'),
            (3, '26-40 years ', NULL, NULL, 'En'),
            (4, '40-65 years ', NULL, NULL, 'En'),
            (5, '65-80 years ', NULL, NULL, 'En'),
            (6, '80-100 years ', NULL, NULL, 'En');

            INSERT INTO `dropdown_type_of_message` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'Email ', NULL, NULL, 'En'),
            (2, 'phone ', NULL, NULL, 'En'),
            (3, 'fax ', NULL, NULL, 'En'),
            (4, 'appointment ', NULL, NULL, 'En'),
            (5, 'memorandum ', NULL, NULL, 'En'),
            (6, 'in memorial ', NULL, NULL, 'En');

            INSERT INTO `dropdown_type_of_service_contract` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, '1 star ', NULL, NULL, 'En'),
            (2, '2 stars ', NULL, NULL, 'En'),
            (3, '3 stars ', NULL, NULL, 'En'),
            (4, '4 stars ', NULL, NULL, 'En'),
            (5, '5 stars ', NULL, NULL, 'En');

            INSERT INTO `dropdown_education` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'university ', NULL, NULL, 'En'),
            (2, 'HBO ', NULL, NULL, 'En'),
            (3, 'MBO ', NULL, NULL, 'En'),
            (4, 'VWO ', NULL, NULL, 'En'),
            (5, 'Havoline ', NULL, NULL, 'En'),
            (6, 'mavo ', NULL, NULL, 'En'),
            (7, 'VMBO ', NULL, NULL, 'En');

            INSERT INTO `dropdown_insurance_status` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'application received ', NULL, NULL, 'En'),
            (2, 'quote needed ', NULL, NULL, 'En'),
            (3, 'rejected ', NULL, NULL, 'En'),
            (4, 'agreement ', NULL, NULL, 'En'),
            (5, 'provisional coverage ', NULL, NULL, 'En');

            INSERT INTO `dropdown_status_mortgages` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'Step 1 ', NULL, NULL, 'En'),
            (2, 'Step 2 ', NULL, NULL, 'En'),
            (3, 'Step 3 ', NULL, NULL, 'En'),
            (4, 'Step 4 ', NULL, NULL, 'En'),
            (5, 'Step 5 ', NULL, NULL, 'En'),
            (6, 'Step 6', NULL, NULL, 'En');

             INSERT INTO `dropdown_type_of_working_contract` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Indefinite contract ', NULL, NULL),
            (2, 'Certain time contract ', NULL, NULL),
            (3, 'Temporary contract ', NULL, NULL),
            (4, 'Posting', NULL, NULL),
            (5, 'Flexi', NULL, NULL);

             INSERT INTO `dropdown_type_of_social_security` (`id`, `name`, `create_date`, `update_date`, `language`) VALUES
            (1, 'WAO ', NULL, NULL, 'En'),
            (2, 'WIA ', NULL, NULL, 'En'),
            (3, 'WW ', NULL, NULL, 'En'),
            (4, 'WAZ ', NULL, NULL, 'En'),
            (5, 'Wajong ', NULL, NULL, 'En');

            INSERT INTO `dropdown_type_of_company` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Eenmanszaak ', NULL, NULL),
            (2, 'v.o.f. ', NULL, NULL),
            (3, 'B.V. ', NULL, NULL),
            (4, 'BVBA ', NULL, NULL);

            INSERT INTO `dropdown_client_insurance_riskscan` (`id`, `name`, `create_date`, `update_date`,`created_by`,`update_by`,`language`) VALUES
            (1, 'Furniture', NULL, NULL, NULL, NULL,'en'),
            (2, 'Docked', NULL, NULL, NULL, NULL,'en'),
            (3, 'Valuable items', NULL, NULL, NULL, NULL,'en'),
            (4, 'AVP', NULL, NULL, NULL, NULL,'en'),
            (5, 'Funeral', NULL, NULL, NULL, NULL,'en'),
            (6, 'Legal aid', NULL, NULL, NULL, NULL,'en'),
            (7, 'Accidents', NULL, NULL, NULL, NULL,'en'),
            (8, 'Car', NULL, NULL, NULL, NULL,'en'),
            (9, 'Motor', NULL, NULL, NULL, NULL,'en'),
            (10, 'Scooter', NULL, NULL, NULL, NULL,'en'),
            (11, 'Oldtimer', NULL, NULL, NULL, NULL,'en'),
            (12, 'Caravan', NULL, NULL, NULL, NULL,'en'),
            (13, 'Travel insurance', NULL, NULL, NULL, NULL,'en'),
            (14, 'Cancel', NULL, NULL, NULL, NULL,'en'),
            (15, 'Permanent health insurance', NULL, NULL, NULL, NULL,'en'),
            (16, 'Inventroy', NULL, NULL, NULL, NULL,'en'),
            (17, 'professional indemnity', NULL, NULL, NULL, NULL,'en'),
            (18, 'Absence due sickness', NULL, NULL, NULL, NULL,'en'),
            (19, 'Vehicle fleet', NULL, NULL, NULL, NULL,'en');

           INSERT INTO `insurance_categories` (`id`, `name`,`sub_category`,`category`, `create_date`, `update_date`) VALUES
            (1, 'Furniture ','Living','Insurance', NULL, NULL),
            (2, 'House ','Living','Insurance', NULL, NULL),
            (3, 'Values ','Living','Insurance', NULL, NULL),
            (4, 'Mobile ','Living','Insurance', NULL, NULL),
            (5, 'Liability insurance','Family','Insurance', NULL, NULL),
            (6, 'Cancellation(short-term)','Family','Insurance', NULL, NULL),
            (7, 'Cancellation(long-term)','Family','Insurance', NULL, NULL),
            (8, 'Annuity','Family','Insurance', NULL, NULL),
            (9, 'Legal assistance','Family','Insurance', NULL, NULL),
            (10, 'Travel insurance(short-term)','Family','Insurance', NULL, NULL),
            (11, 'Travel insurance(long-term)','Family','Insurance', NULL, NULL),
            (12, 'Funeral','Family','Insurance', NULL, NULL),
            (13, 'Windsurfing board','Family','Insurance', NULL, NULL),
            (14, 'Accidents','Family','Insurance', NULL, NULL),
            (15, 'Term life insurance','Family','Insurance', NULL, NULL),
            (16, 'Medical Insurance','Family','Insurance', NULL, NULL),
            (17, 'Package Family','Family','Insurance', NULL, NULL),
            (18, 'Car ','Transportation','Insurance', NULL, NULL),
            (19, 'Vans ','Transportation','Insurance', NULL, NULL),
            (20, 'Motor','Transportation','Insurance', NULL, NULL),
            (21, 'Moped ','Transportation','Insurance', NULL, NULL),
            (22, 'Oldtimer','Transportation','Insurance', NULL, NULL),
            (23, 'Quad','Transportation','Insurance', NULL, NULL),
            (24, 'Trailer ','Transportation','Insurance', NULL, NULL),
            (25, 'Mobile home','Transportation','Insurance', NULL, NULL),
            (26, 'Boot','Transportation','Insurance', NULL, NULL),
            (27, 'Bi-cycle ','Transportation','Insurance', NULL, NULL),
            (28, 'Golf','Diversion','Insurance', NULL, NULL),
            (29, 'Dog','Diversion','Insurance', NULL, NULL),
            (30, 'Horses','Diversion','Insurance', NULL, NULL),
            (31, 'Company Liability','Company','Insurance', NULL, NULL),
            (32, 'Company buildings','Company','Insurance', NULL, NULL),
            (33, 'Company Damages','Company','Insurance', NULL, NULL),
            (34, 'Profession Liability','Company','Insurance', NULL, NULL),
            (35, 'MKB Package','Company','Insurance', NULL, NULL),
            (36, 'Garage','Company','Insurance', NULL, NULL),
            (37, 'Airplane','Company','Insurance', NULL, NULL),
            (38, 'Tools','Company','Insurance', NULL, NULL),
            (39, 'Trucks','Company','Insurance', NULL, NULL),
            (40, 'Car-park','Company','Insurance', NULL, NULL),
            (41, 'Events','Company','Insurance', NULL, NULL),
            (42, 'WEGAM','Company','Insurance', NULL, NULL),
            (43, 'Sickness absence','Company','Insurance', NULL, NULL),
            (44, 'ZZP Package','Company','Insurance', NULL, NULL),
            (45, 'Company Legal Assistance','Company','Insurance', NULL, NULL),
            (46, 'Collective Business Travel','Company','Insurance', NULL, NULL),
            (47, 'Inventory','Company','Insurance', NULL, NULL),
            (48, 'C.A.R.','Company','Insurance', NULL, NULL),
            (49, 'Disability Insurance(OA/WW)','Mortgage','Insurance', NULL, NULL),
            (50, 'Investment','Mortgage','Insurance', NULL, NULL),
            (51, 'Capital','Mortgage','Insurance', NULL, NULL),
            (52, 'Life Insurance','Mortgage','Insurance', NULL, NULL),
            (53, 'Term life insurance','Mortgage','Insurance', NULL, NULL),
            (54, 'Savings','Mortgage','Insurance', NULL, NULL),
            (55, 'Mortgage Offer','Mortgage','Insurance', NULL, NULL),
            (56, 'Bank Guarantee Offer','Mortgage','Insurance', NULL, NULL);



            INSERT INTO `dropdown_action` (`id`, `name`, `create_date`, `update_date`) VALUES
            (1, 'Trips & Vacations', NULL, NULL),
            (2, 'Fashion & Shopping', NULL, NULL),
            (3, 'Electronics & Gadgets', NULL, NULL),
            (4, 'Telephone & Internet', NULL, NULL),
            (5, 'Gas & Light', NULL, NULL);

        ");
	}

	public function safeDown()
	{
        $this->execute("DELETE FROM `dropdown_banks` WHERE `id` < 52");
        $this->execute("DELETE FROM `dropdown_car_insurance_mileage_per_year` WHERE `id` < 9");
        $this->execute("DELETE FROM `dropdown_county` WHERE `id` < 13");
        $this->execute("DELETE FROM `dropdown_credit_banks` WHERE `id` < 24");
        $this->execute("DELETE FROM `dropdown_credit_card_banks` WHERE `id` < 20");
        $this->execute("DELETE FROM `dropdown_department` WHERE `id` < 8");
        $this->execute("DELETE FROM `dropdown_document_type` WHERE `id` < 8");
        $this->execute("DELETE FROM `dropdown_family_composition` WHERE `id` < 7");
        $this->execute("DELETE FROM `dropdown_functions` WHERE `id` < 8");
        $this->execute("DELETE FROM `dropdown_insurers` WHERE `id` < 104");
        $this->execute("DELETE FROM `dropdown_insurer_for_redemption_of_mortgage` WHERE `id` < 106");
        $this->execute("DELETE FROM `dropdown_load_box` WHERE `id` < 4");
        $this->execute("DELETE FROM `dropdown_marital_status` WHERE `id` < 11");
        $this->execute("DELETE FROM `dropdown_nations` WHERE `id` < 257");
        $this->execute("DELETE FROM `dropdown_payment` WHERE `id` < 5");
        $this->execute("DELETE FROM `dropdown_pension_funds_and_pension_insurers` WHERE `id` < 98");
        $this->execute("DELETE FROM `dropdown_period_salary` WHERE `id` < 4");
        $this->execute("DELETE FROM `dropdown_property_type` WHERE `id` < 11");
        $this->execute("DELETE FROM `dropdown_repayment_rortgage_rorm` WHERE `id` < 10");
        $this->execute("DELETE FROM `dropdown_status_damages` WHERE `id` < 5");
        $this->execute("DELETE FROM `dropdown_subscriptions` WHERE `id` < 9");
        $this->execute("DELETE FROM `dropdown_type_of_benefit` WHERE `id` < 5");
        $this->execute("DELETE FROM `dropdown_type_of_coverage_by_insurance` WHERE `id` < 273");
        $this->execute("DELETE FROM `dropdown_type_of_employment` WHERE `id` < 10");
        $this->execute("DELETE FROM `dropdown_type_of_health_insurance` WHERE `id` < 5");
        $this->execute("DELETE FROM `dropdown_type_of_insurance` WHERE `id` < 43");
        $this->execute("DELETE FROM `dropdown_type_of_loan` WHERE `id` < 6");
        $this->execute("DELETE FROM `dropdown_type_of_loans` WHERE `id` < 12");
        $this->execute("DELETE FROM `dropdown_type_of_maintenance` WHERE `id` < 3");
        $this->execute("DELETE FROM `dropdown_type_of_mortgage` WHERE `id` < 11");
        $this->execute("DELETE FROM `dropdown_type_of_retirement` WHERE `id` < 10");
        $this->execute("DELETE FROM `dropdown_ww_type_insurance` WHERE `id` < 4");
        $this->execute("DELETE FROM `dropdown_role` WHERE `id` < 5");
        $this->execute("DELETE FROM `dropdown_type` WHERE `id` < 6");
        $this->execute("DELETE FROM `dropdown_type_advice` WHERE `id` < 6");
        $this->execute("DELETE FROM `dropdown_bkr_code` WHERE `id` < 4");
        $this->execute("DELETE FROM `dropdown_type_of_customer` WHERE `id` < 7");
        $this->execute("DELETE FROM `dropdown_type_of_message` WHERE `id` < 7");
        $this->execute("DELETE FROM `dropdown_type_of_service_contract` WHERE `id` < 6");
        $this->execute("DELETE FROM `dropdown_education` WHERE `id` < 8");
        $this->execute("DELETE FROM `dropdown_insurance_status` WHERE `id` < 6");
        $this->execute("DELETE FROM `dropdown_status_mortgages` WHERE `id` < 7");
        $this->execute("DELETE FROM `dropdown_type_of_working_contract` WHERE `id` < 6");
        $this->execute("DELETE FROM `dropdown_type_of_social_security` WHERE `id` < 6");
        $this->execute("DELETE FROM `dropdown_type_of_company` WHERE `id` < 5");
        $this->execute("DELETE FROM `dropdown_client_insurance_riskscan` WHERE `id` < 20");
        $this->execute("DELETE FROM `insurance_categories` WHERE `id` < 50");
        $this->execute("DELETE FROM `dropdown_action` WHERE `id` < 6");



    }

}